- testsuite/SConscript
> Removing maketx and the references to it

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
> [General] Setting up initial issue and pull request templates.

- .gitignore
- cmd/SConscript
- plugInfo.json
- render_delegate/material.cpp
- Add missing "main" plugInfo.json file
- Fix compilation error on OSX and missing library in usd_translator
> Build fixes

- third_party/houdini/scripts/python/husdshadertranslators/arnold.py
- third_party/houdini/soho/parameters/HdArnoldRendererPlugin_Geometry.ds
I noticed some changes that got left out from the open-source release.
- Updating arnold.py and the render settings script.
No issues created for this pull request.
> [Third Party] Leftover changes missing from the open-source release

- render_delegate/utils.cpp
- Updating `_Declare` in `render_delegate/utils.cpp` to allow overwriting existing declarations.
Fixes #3
> Support dirtying and syncing of primvars.

- translator/reader/read_geometry.cpp
- translator/reader/registry.h
- Including <ai.h> instead of individual headers to solve Arnold 5 vs 6 compatibility issue.
- Fixing missing parameter from `exportMatrix` calls.
Fixes #66
> Fixing build issues when using Arnold 5.4.

- render_delegate/mesh.cpp
- When the topology received from Hydra is leftHanded, flip the polygon order to match Arnold's standard.
Fixes #83
> Flipping polygon order if the topology orientation is left handed in the render delegate

- SConstruct
- Change the location of .sconsign.dblite and include the scons verions in its name
Fixes #115
> Change the location of .sconsign.dblite and include the scons verions in its name

- render_delegate/constant_strings.h
- render_delegate/render_pass.cpp
- Change the default filter to box from gaussian for the beauty pass.
Fixes #117
> Change the default filter to box from gaussian for the beauty pass.

- README.md
- Add ARNOLD_PLUGIN_PATH documentation in README.md
> Add ARNOLD_PLUGIN_PATH documentation in README.md

- render_delegate/mesh.cpp
- Converting normal primvars to nlist and nidxs
- Unifying normal and uv handling code
- Reading points during primvar iteration
Fixes #1
> Supporting custom vertex normals for polymeshes.

- SConstruct
- docs/building.md
- render_delegate/SConscript
- render_delegate/volume.cpp
- render_delegate/volume.h
- Removing BUILD_HOUDINI_TOOLS and all associated documentation from the build and codebase
Fixes #114
> Removing BUILD_HOUDINI_TOOLS and all associated documentation from the build and codebase

- translator/reader/prim_reader.cpp
- Check for both `std::string` and `TfToken` when reading in enum and string attributes. This removes an error message.
- Check for empty arrays and invalid queries when accessing the matrix array attribute on Arnold shapes.
Fixes #135
> Fixing a crash in the procedural when matrix arrays are empty

- render_delegate/constant_strings.h
- Adding `nlist` and `nidxs` to `render_delegate/constant_strings.h`
- Fixing the doxygen tag for `render_delegate/constant_strings.h`
Fixes #140
> Missing bits from pull request 133

- SConstruct
- procedural/SConscript
This patch was provided by Oscar Anson, it adds build variables to Scons in order to control the SDK version and path.
Fixes #143
> Add build variables for sdk path and version

- cmd/SConscript
- procedural/SConscript
Link the procedural against `pthread `and `dl` . This change was proposed by Oscar Anson in order to fix the current linux builds.
Fixes #147
> Link linux builds against pthread and dl

- render_delegate/material.cpp
- Turning off Katana 32 specific code when using a newer usd build.
Fixes #160
> Fixing build issue with the latest USD releases

- SConstruct
- procedural/SConscript
- procedural/main.cpp
- tools/utils/build_tools.py
- Automatically detect if ai_scene_format.h is available.
Fixes #173
> Automatically detect if ai_scene_format.h is available.

- testsuite/test_0014/data/scene.usda
- Updating scene file for test 14
Fixes #155
> Updating scene file for test 14

- procedural/SConscript
- procedural/main.cpp
- Applying the OSX fix of delaying the USD library load to Linux
Fixes #199
> Applying the OSX fix of delaying the USD library load to Linux

- render_delegate/mesh.cpp
- render_delegate/mesh.h
- render_delegate/utils.cpp
- render_delegate/utils.h
- Support leftHanded topologies for faceVarying primvars, including specialized path for uvs and normals.
Fixes #207
> Support leftHanded topologies for face varying primvars

- render_delegate/instancer.cpp
- render_delegate/instancer.h
- render_delegate/mesh.cpp
- render_delegate/shape.cpp
- render_delegate/shape.h
- render_delegate/utils.cpp
- render_delegate/utils.h
- render_delegate/volume.cpp
- render_delegate/volume.h
- Fixing matrix updates for instances
- Supporting volume instances
- Fixing source mesh visibility
- Reading constant primvars for volumes
- Changing how instancer primvars are stored
- Improving HdArnoldSetTransform safety
Fixes #18
Fixes #123
> Improving support for hydra point instancer

- render_delegate/points.cpp
- Adding support for uniform point primvars.
Fixes #228
> Adding support for uniform point primvars.

- render_delegate/mesh.cpp
- render_delegate/mesh.h
- render_delegate/utils.cpp
- render_delegate/utils.h
- Matching the number of motion keys between position and normal on the mesh.
Fixes #229
> Matching the number of motion keys between position and normal on the mesh

- tools/scons-custom/site_tools/clang.py
This patch was sent by Oscar Anson, it's the change that had to be done to the alembic procedural for clang9 builds on linux. 
I haven't been able to test it yet, so this code should be tested in the proper environment before it's merged.
Fixes #252
> Fix build with clang9

- SConstruct
- cmake/modules/FindUSD.cmake
- render_delegate/CMakeLists.txt
- render_delegate/SConscript
- render_delegate/render_pass.cpp
- render_delegate/render_pass.h
- tools/utils/build_tools.py
- Using HdxFullscreenShader instead of HdxCompositor if header is available.
Fixes #258
> Fixing render delegate compilation issue with latest USD dev

- CHANGELOG.md
- Create release notes for 6.0.2.1.
Fixes #261
> Create release notes for 6.0.2.1.

- render_delegate/render_delegate.cpp
- Clearing out leftover code referring to BUILD_HOUDINI_TOOLS
Fixes #268
> Clearing out leftover code referring to BUILD_HOUDINI_TOOLS

- README.md
This PR updates the documentation with the latest enhancements
Fixes #204
> Updating documentation with latest features

- render_delegate/shape.h
- Set the default value of the instancer to nullptr on the shape.
Fixes #298
> Setting instancer to nullptr on the shape. 

- procedural/main.cpp
Simple change to prevent the build issues on linux and Mac that were introduced in #297 
Fixes #303
> Fix build issue on linux and mac

- render_delegate/hdarnold.h
- render_delegate/mesh.cpp
- render_delegate/utils.cpp
- Fixing the render delegate build when using USD-0.19.05.
Fixes #306
> Fixing the render delegate build when using USD-0.19.05.

- procedural/main.cpp
Still trying to fix the build issues on Mac (while using the arnold toolchain) introduced in #297 and #303
> Another fix for builds on Mac

- translator/writer/write_geometry.cpp
We need to do a special case for `num_points` and explicitely write it as an INT-Array attribute instead of relying on the automatic conversion that would try to write it as a UINT array
Fixes #324
> Write curves num points as a int-array

- translator/CMakeLists.txt
- Adding new options writer files to cmake
Fixes #320
> Adding new options writer files to cmake

- translator/writer/write_geometry.cpp
The mesh writer is now writing all the eventual motion keys for the normals list. This is needed, since otherwise arnold complains when the amount of keys in `vlist` is different from the keys in `nlist`.
Fixes #356
> Write motion keys in mesh normals list

- docs/conventions.md
- ndr/parser.cpp
- ndr/parser.h
- render_delegate/config.h
- render_delegate/constant_strings.h
- render_delegate/material.cpp
- render_delegate/mesh.cpp
- render_delegate/render_buffer.cpp
- render_delegate/utils.cpp
- render_delegate/volume.cpp
- Updating the render delegate and the ndr plugin to follow the coding conventions.
- Extending the coding conventions document.
Only WIP for #372 .
> Updating the render delegate and the ndr plugin to follow the coding conventions.

- cmd/main.cpp
- procedural/main.cpp
- testsuite/test_0045/data/test.cpp
- translator/reader/prim_reader.cpp
- translator/reader/prim_reader.h
- translator/reader/read_arnold_type.cpp
- translator/reader/read_arnold_type.h
- translator/reader/read_geometry.cpp
- translator/reader/read_light.cpp
- translator/reader/read_shader.cpp
- translator/reader/reader.cpp
- translator/reader/reader.h
- translator/reader/registry.cpp
- translator/reader/registry.h
- translator/reader/utils.cpp
- translator/reader/utils.h
- translator/utils/utils.h
- translator/writer/prim_writer.cpp
- translator/writer/prim_writer.h
- translator/writer/registry.cpp
- translator/writer/registry.h
- translator/writer/write_arnold_type.cpp
- translator/writer/write_arnold_type.h
- translator/writer/write_geometry.cpp
- translator/writer/write_light.cpp
- translator/writer/write_options.cpp
- translator/writer/write_shader.cpp
- translator/writer/write_shader.h
- translator/writer/writer.cpp
- translator/writer/writer.h
- Updating the translator, procedural and the cmd code to following coding guidelines
#372
> Updating the translator, procedural and the cmd code to following coding guidelines

- SConstruct
- Do not validate the google test include and library directories.
Fixes #387
> Do not validate the google test include and library directories

- render_delegate/nodes/driver.cpp
- Setting background pixel depth to 1 instead of 1 - AI_EPSILON.
Fixes #385
> Setting background pixel depth to 1 instead of 1 - AI_EPSILON.

- CHANGELOG.md
- Adding release notes for 6.0.3.0.
> Adding release notes for 6.0.3.0.

- testsuite/test_0050/README
- tools/utils/regression_test.py
#403 didn't finish the job, there was still another part of the testsuite scripts that had to be modified in order to match the python tools used by arnold
Fixes #402
> Fix testsuite scripts to match arnold python tools #402

- render_delegate/constant_strings.h
- render_delegate/nodes/driver.cpp
- render_delegate/render_buffer.h
- render_delegate/render_pass.cpp
- render_delegate/render_pass.h
- Reading filter parameters from the aovSettings map for the render buffers.
Fixes #319
> Reading filter parameters from the aovSettings map for the render buffers

- testsuite/groups
- Re-enabling test 62 and 68.
Fixes #414
> Re-enabling test 62 and 68

- ndr/utils.cpp
- render_delegate/render_delegate.cpp
- translator/reader/registry.cpp
- translator/writer/registry.cpp
- Remove uses of AiLoadPlugins.
Fixes #418
> Remove uses of AiLoadPlugins

- render_delegate/render_pass.cpp
- Setting the elementId, instanceId and pointId AOV to converged and setting its value.
Fixes #431
> Setting the elementId, instanceId and pointId AOV to converged and setting its value.

- SConstruct
- Adding a new scons variable to set the CXX_STANDARD.
Fixes #446
> Adding a new scons variable to set the CXX_STANDARD

- render_delegate/render_pass.cpp
- Searching for filter parameters under an alternate prefix.
Fixes #437
> Searching for filter parameters under an alternate prefix.

- render_delegate/nodes/driver_main.cpp
- render_delegate/render_pass.cpp
- Using the dataType aovSetting correctly.
- In case of a -1 ID, setting only the alpha to zero, instead of making the rgba color zero.
Fixes #450
> Using the dataType aovSetting correctly.

- CHANGELOG.md
- README.md
- Updating release notes and readme for 6.0.3.1.
> Updating release notes and readme for 6.0.3.1.

- schemas/createSchemaFile.py
- testsuite/SConscript
- testsuite/test_0015/ref/reference.log
- tools/utils/contrib/bottle/__init__.py
- Removing insensitive terminology.
Fixes #469
> Removing insensitive terminology

- render_delegate/hdarnold.h
- render_delegate/mesh.cpp
- render_delegate/render_pass.cpp
- render_delegate/render_pass.h
- Fixing compatibility with USD 20.08.
Fixes #477
> Fixing compatibility with USD 20.08

- render_delegate/instancer.cpp
- render_delegate/instancer.h
- render_delegate/mesh.cpp
- render_delegate/shape.cpp
- render_delegate/utils.cpp
- render_delegate/utils.h
- Adding support for per-instance primvars.
Fixes #471
> Adding support for per instance primvars

- render_delegate/CMakeLists.txt
- render_delegate/SConscript
- render_delegate/basis_curves.cpp
- render_delegate/basis_curves.h
- render_delegate/constant_strings.h
- render_delegate/debug_codes.cpp
- render_delegate/debug_codes.h
- render_delegate/material.h
- render_delegate/render_delegate.cpp
- render_delegate/utils.cpp
- render_delegate/utils.h
- testsuite/CMakeLists.txt
- testsuite/groups
- testsuite/test_0136/README
- testsuite/test_0136/data/test.cpp
- Adding support for rendering basis curves.
- Added unit test 0136 to test some of the new utility functions.
Fixes #19
> Initial support for curve rendering.

- SConstruct
- Allow overwriting the build directory.
Fixes #490
> Allow overwriting the build directory

- docs/building.md
- Documenting the use of the CMake build system.
Fixes #125
> Documenting the use of the CMake build system

- CHANGELOG.md
- README.md
- Updating readme and release notes for the 6.0.4.0 release.
Fixes #494
> Updating readme and release notes for the 6.0.4.0 release

- schemas/createSchemaFile.py
The schemas build was outdated. This PR is about ensuring it's in-line with the behaviour in the translator and render_delegate.
Here's the list of changes :
- Base typed schemas for common types (`ArnoldShape`, `ArnoldOperator`, etc...) now inherit from the base schema typed instead of a corresponding usd builtin schema. They are now declared as being non-instantiable.
- API schemas for common types (`ArnoldShapeAPI`, `ArnoldLightAPI`, `ArnoldCameraAPI`) now define the correct list of attributes ((they ignore the ones already present in the USD builtin schema)
- API schemas for  "leaf" classes (`ArnoldPolymeshAPI`, `ArnoldSkydomeLightAPI`, etc...) inherit from the corresponding base API schema mentioned above. They ignore the attributes already …
> Improve the schemas builds

- SConstruct
- testsuite/SConscript
- testsuite/test_0136/data/test.cpp
- tools/utils/regression_test.py
- Allow using an external directory for test references.
- Using the oiiotool from the Arnold SDK and removing the oiiotool executables from contrib.
- Fixing test 136.
Fixes #507
> Using reference images from an external folder

- render_delegate/material.cpp
- render_delegate/material.h
- Removing Katana 3.2 specific code.
Fixes #525
> Removing Katana 3.2 specific code

- render_delegate/material.cpp
- Removing the use of pxr:: from material.cpp.
Fixes #528
> Removing the use of pxr:: from material.cpp

- docs/conventions.md
- Documenting the use of the pxr namespace macros.
Documentation for #528
> Documenting the use of the pxr namespace macros

- render_delegate/light.cpp
- Fixing the cylinder light axis.
Fixes #530
> Fixing the cylinder light axis

- SConstruct
- Adding BOOST_ALL_NO_LIB build option.
Fixes #533
> Adding BOOST_ALL_NO_LIB build option

- render_delegate/constant_strings.h
- render_delegate/render_delegate.cpp
- render_delegate/render_delegate.h
- Implementing GetRenderStats and returning percentage done.
Fixes #537
> Implementing GetRenderStats and returning percentage done

- SConstruct
- Installing license file.
Fixes #540
> Installing license file

- schemas/CMakeLists.txt
- schemas/SConscript
- schemas/updatePlugInfo.py
- Fixing updatePlugInfo.py with newer USD builds.
Fixes #560
> Fixing updatePlugInfo.py with newer USD builds

- render_delegate/hdarnold.h
- render_delegate/nodes/driver_main.cpp
- Changing depth range from -1..1 to 0..1 if USD is at least 20.02.
Fixes #580
> Changing depth range from -1..1 to 0..1 if USD is at least 20.02

- render_delegate/constant_strings.h
- render_delegate/light.cpp
- Add support for treatAsPoint on the sphere light.
Fixes #577
> Add support for treatAsPoint on the sphere light

- CHANGELOG.md
- Adding release notes for 6.1.0.0.
Fixes #585
> Adding release notes for 6.1.0.0.

- render_delegate/mesh.cpp
- render_delegate/mesh.h
- render_delegate/utils.cpp
- render_delegate/utils.h
- testsuite/groups
- testsuite/test_0147/README
- testsuite/test_0147/data/test.cpp
- Fixing issues related to invalid face-varying primvars in usd stages.
Fixes #592
> Fixing issues related to invalid face-varying primvars in usd stages

- SConstruct
- cmake/utils/options.cmake
- procedural/CMakeLists.txt
- procedural/SConscript
- procedural/main.cpp
- Allow overwriting the usd procedural name.
- Removing prefix 3rd party option from scons.
Fixes #600
> Allow overwriting the usd procedural name.

- render_delegate/SConscript
- Add missing comma from render_delegate/SConscript.
#31
> Missing comma from render_delegate/SConscript.

- render_delegate/mesh.cpp
- Counting the faceVertexCounts for right-handed meshes for primvar validation.
Fixes #605
> Counting the faceVertexCounts for right-handed meshes for primvar validation

- render_delegate/camera.cpp
- Support Arnold specific hydra camera parameters.
Fixes #611
> Support Arnold specific hydra camera parameters

- render_delegate/render_pass.cpp
- Extending _GetArnoldTypesFromTokenType with more types and renaming the function.
Fixes #619
> Extending _GetArnoldTypesFromTokenType with more types

- schemas/createSchemaFile.py
- Inheriting from XFormable for shape, light and camera schemas.
Fixes #558
> Inheriting from XFormable for shape, light and camera schemas

- translator/writer/write_arnold_type.cpp
- translator/writer/write_geometry.cpp
When writing to USD, all shapes now write the `extent` attribute so that it's faster to load their bounding boxes.
For procedurals, I need to call the viewport API in boxes mode and get the resulting bounding box, so we can probably expect an overhead when writing out to usd with procedurals. But this time should be worth it as it should make it much faster to read and display in the viewport.
Fixes #582
> Author extents on shapes when writing to USD

- translator/writer/write_arnold_type.cpp
- translator/writer/write_geometry.cpp
pull request #628 was missing a few fixes. First, for arnold schemas, we shouldn't call `GetExtentAttr` but `CreateExtentAttr` to ensure this parameter exists at first.
Second, the function `AiSceneUniverseGetSceneBounds` doesn't seem to work if the universe wasn't initialized for rendering. So instead, we need to loop over all of this procedural's childs and compute the bounding box ourselves
Fixes #582
> More fixes on writing procedurals extents

- render_delegate/mesh.cpp
- render_delegate/points.cpp
- render_delegate/utils.cpp
- Fixing disappearing meshes when playing back animation
- Removing dead code
Fixes #634
> Fixing disappearing meshes when playing back animation

- render_delegate/camera.cpp
- Fixing build issues using gcc-4.8.5.
Fixes #641
> Fixing build issues using gcc-4.8.5

- CHANGELOG.md
Updating release notes for 6.2.0.0.
> Updating release notes.

- render_delegate/points.cpp
- Syncing transformation for the points primitive.
Fixes #654
> Syncing transformation for the points primitive

- render_delegate/basis_curves.cpp
- render_delegate/basis_curves.h
- render_delegate/hdarnold.h
- render_delegate/instancer.cpp
- render_delegate/instancer.h
- render_delegate/light.cpp
- render_delegate/mesh.cpp
- render_delegate/mesh.h
- render_delegate/points.cpp
- render_delegate/points.h
- render_delegate/render_delegate.cpp
- render_delegate/render_delegate.h
- render_delegate/rprim.h
- render_delegate/volume.cpp
- render_delegate/volume.h
- Fixing compilation issues with 21.02.
There are still issues with the new framing API so the render delegate will render black in usdview.
> Fixing compilation issues with USD 21.02. (#656)

- docs/building.md
- render_delegate/CMakeLists.txt
- render_delegate/hdarnold.h
- render_delegate/instancer.cpp
- render_delegate/material.cpp
- render_delegate/render_pass.cpp
- render_delegate/renderer_plugin.cpp
- render_delegate/renderer_plugin.h
- tools/utils/dependencies.py
- Fixing the behavior of the render delegate with 21.02. 
- Raising the minimum required USD to 19.11.
Fixes #656
> Fixing the behavior of the render delegate with 21.02

- render_delegate/basis_curves.cpp
- render_delegate/instancer.cpp
- render_delegate/instancer.h
- render_delegate/mesh.cpp
- render_delegate/render_delegate.cpp
- render_delegate/rprim.h
- render_delegate/shape.cpp
- render_delegate/shape.h
- render_delegate/utils.cpp
- render_delegate/utils.h
- Initial take on motion blurring of the point instancer.
#653 is not fixed by this change, there are still differences when comparing to karma.
> Initial take on motion blurring of the point instancer

- render_delegate/constant_strings.h
- render_delegate/render_delegate.cpp
- render_delegate/render_delegate.h
- render_delegate/render_pass.cpp
- render_delegate/rprim.h
- render_delegate/shape.cpp
- render_delegate/volume.cpp
- Fixing bugs and adding missing features for motion blurred instancers.
- Adding support for the `instantaneousShutter` render setting.
Fixes #653
> Fixing bugs and adding missing features for motion blurred instancers.

- render_delegate/utils.cpp
- testsuite/groups
- testsuite/test_0152/README
- testsuite/test_0152/data/test.cpp
- testsuite/test_0153/README
- testsuite/test_0153/data/test.cpp
- testsuite/test_0154/README
- testsuite/test_0154/data/test.cpp
- testsuite/test_0155/README
- testsuite/test_0155/data/test.cpp
- testsuite/test_0156/README
- testsuite/test_0156/data/test.cpp
- Adding support for half/double types/tuples in HdArnold* utility functions
Fixes #669
> Adding support for half/double types/tuples in HdArnold* utility functions

- render_delegate/render_delegate.cpp
- render_delegate/render_delegate.h
- render_delegate/render_param.cpp
- render_delegate/render_param.h
- render_delegate/render_pass.cpp
- Adding support for the pause/resume API.
Fixes #595
> Adding support for the pause/resume API

- CMakeLists.txt
- SConstruct
- cmake/utils/options.cmake
- schemas/CMakeLists.txt
- schemas/SConscript
- schemas/updatePlugInfo.py
- Removing the build of the c++ schemas and the python libraries.
- Adding new build variables to specify schema installation directory.
- Fixing the schemas so they work without a c++ library.
- Allow generating the schemas when using a static USD build, given that UsdGenSchema exists.
Fixes #705
> Simplifying schema build and installation

- schemas/SConscript
- Using USD_PATH instead of USD_LOCATION + bin in schemas/SConscript.
Fixes #707
> Using USD_PATH instead of USD_LOCATION + bin in schemas/SConscript

- ndr/CMakeLists.txt
- ndr/SConscript
- render_delegate/CMakeLists.txt
- render_delegate/SConscript
- render_delegate/material.cpp
- tools/utils/dependencies.py
- translator/CMakeLists.txt
- translator/SConscript
- usd_imaging/CMakeLists.txt
- usd_imaging/SConscript
- Fixing initialization order issues related to constant_strings.h.
Fixes #715
> Fixing initialization order issues related to constant_strings.h

- schemas/SConscript
- Clearing PYTHONPATH before running usdGenSchema
- Adding USD_BIN to the PATH before running usdGenSchema
Fixes #722
> Fixing build issues on macOS and targeting Houdini USD libraries

- common/constant_strings.h
- render_delegate/render_delegate.cpp
- Change render context hint from interactive to hydra.
Change for the already closed #711 , something that's more accurate.
> Change render context hint from interactive to hydra. (#711)

- SConstruct
- Optionally adding the arnold binaries to the RPATH.
Fixes #670
> Optionally adding the arnold binaries to the RPATH

- usd_imaging/CMakeLists.txt
- usd_imaging/shape_adapter.cpp
- usd_imaging/shape_adapter.h
- usd_imaging/usd_lux_light_filter_adapter.cpp
- Fixing build issues in usd_imaging/shape_adapter related to the additional parameter in the Get function.
- Fixing build issues in `usd_lux_light_filter_adapter.cpp` related to a function now missing.
Related to #764
> Fixing usd_imaging compilation issues when targeting 21.05. (#765)

- CHANGELOG.md
- README.md
- Updating changelog and readme.
Fixes #773
> Updating changelog and readme

- render_delegate/utils.cpp
- testsuite/test_0134/data/test.cpp
- Converting GfMatrix4d attributes to AI_TYPE_MATRIX parameters.
- Testing matrix conversion in test_0134.
- Running clang-format on test_0134.
Fixes #795
> Converting GfMatrix4d attributes to AI_TYPE_MATRIX parameters

- render_delegate/mesh.cpp
- Reset disp_map instead of setting nullptr array
Fixes #790
> Reset disp_map instead of setting nullptr array. (#790)

- ndr/discovery.cpp
- ndr/plugInfo.json.in
- ndr/utils.cpp
- Renaming metadata used by ndr plugin.
Fixes #798
> Renaming metadata used by ndr plugin

- schemas/SConscript
- Fixing schemas build when there are spaces in the project folder path.
Fixes #810
> Fixing schemas build when there are spaces in the project folder path

- cmake/utils/test.cmake
- testsuite/CMakeLists.txt
- Running unit tests via CMake.
This is some of the already existing code in my fork, so pushing further patches for the rest of the testsuite work will be cleaner.
> Running unit tests via CMake

- ndr/discovery.cpp
- ndr/discovery.h
- ndr/parser.cpp
- Fixing build issue with 21.08.
- Removing default constructor and destructor of NdrArnoldDiscoveryPlugin which is not needed.
Fixes #835
> Fixing build issue with USD 21.08

- schemas/createSchemaFile.py
- Fixing the use of iteritems with python 3.
Fixes #837
> Fixing the use of iteritems with python 3

- ndr/utils.cpp
- Not using AiArrayGetXXXFuncs anymore.
Fixes #849
> Not using AiArrayGetXXXFuncs anymore

- SConstruct
- Configuring plugInfo.json files in the build directory.
Fixes #851
> Configuring plugInfo.json files in the build directory

- ndr/utils.cpp
- Fixing the build of master using the latest Arnold release.
This was a build regression introduced for the fix in #849.
> Fixing the build of master using the latest Arnold release

- common/constant_strings.h
- render_delegate/nodes/driver_aov.cpp
- render_delegate/nodes/driver_main.cpp
- Cleaning up AiOutputIteratorGetNext changes.
Fixes #845
> Cleaning up AiOutputIteratorGetNext changes

- render_delegate/light.cpp
- Checking for visibility when syncing lights.
Fixes #858
> Checking for visibility when syncing lights

- schemas/createSchemaFile.py
- Improving createSchemaFile python3 compatibility.
Fixes #837
Used futurize for a better recommendation.
> Improving createSchemaFile python3 compatibility

- render_delegate/mesh.cpp
- Validating facevarying indices of primvars.
Fixes #853
> Validating facevarying indices of primvars.

- testsuite/test_0015/data/scene.usda
- testsuite/test_0140/data/test.usda
- testsuite/test_0181/data/test.usda
- translator/reader/read_light.cpp
> Merging fix branch to master.

- render_delegate/render_buffer.cpp
- render_delegate/render_delegate.cpp
- render_delegate/render_delegate.h
- render_delegate/render_pass.cpp
- render_delegate/rprim.h
- render_delegate/shape.cpp
- render_delegate/shape.h
- render_delegate/volume.cpp
- Adding support for render tags in the render delegate.
Fixes # 843
> Support render tags in the render delegate.

- render_delegate/render_buffer.cpp
- render_delegate/render_delegate.cpp
- render_delegate/render_delegate.h
- render_delegate/render_pass.cpp
- render_delegate/rprim.h
- render_delegate/shape.cpp
- render_delegate/shape.h
- render_delegate/volume.cpp
- testsuite/test_0015/data/scene.usda
- testsuite/test_0140/data/test.usda
- testsuite/test_0181/data/test.usda
- translator/reader/read_light.cpp
> Updating master with changes from the fix branch

- render_delegate/utils.cpp
- testsuite/test_0134/data/test.cpp
- Converting integer parameters to unsigned int.
- Converting unsigned int to int.
- Converting unsigned int to byte.
Fixes #887
> Improving conversions between integer types.

- render_delegate/nodes/driver_aov.cpp
- render_delegate/render_pass.cpp
- Fixing the use of AI_TYPE_INT AOVs.
- Removing a warning when setting blend_opacity.
Fixes #905
> Fixing the use of AI_TYPE_INT AOVs

- ndr/discovery.cpp
- Setting the returned version to default in the Sdr plugin.
Fixes #906
> Setting the returned version to default in the Sdr plugin

- ndr/discovery.cpp
- render_delegate/nodes/driver_aov.cpp
- render_delegate/render_buffer.cpp
- render_delegate/render_delegate.cpp
- render_delegate/render_delegate.h
- render_delegate/render_param.cpp
- render_delegate/render_pass.cpp
- render_delegate/rprim.h
- render_delegate/shape.cpp
- render_delegate/shape.h
- render_delegate/utils.cpp
- render_delegate/volume.cpp
- testsuite/test_0015/data/scene.usda
- testsuite/test_0134/data/test.cpp
- testsuite/test_0140/data/test.usda
- testsuite/test_0181/data/test.usda
- translator/reader/read_light.cpp
- Fixing the use of AI_TYPE_INT AOVs.
- Removing a warning when setting blend_opacity.
- Setting the returned version to default in the Sdr plugin.
- Avoid calling AiRenderBegin when render is already running.
- Passing render session to AiDeviceAutoSelect.
Fixes #905
Fixes #906
Fixes #900
Fixes #902
> Merging fix-7.0.0 to master

- CHANGELOG.md
- README.md
- docs/building.md
- Updating changelog for Arnold 7.
- Updating readme for Arnold 7.
- Updating building.md with the new USD version supported.
Fixes #897
> Updating changelog and readme for Arnold 7.

- render_delegate/render_delegate.cpp
- Changing the default descriptor returned for AOVs.
Fixes #918
> Changing the default descriptor returned for AOVs

- CHANGELOG.md
- Update changelog for the 7.0.0.1 release.
Fixes #935
> Update changelog for the 7.0.0.1 release

- SConstruct
- render_delegate/CMakeLists.txt
- render_delegate/render_pass.h
- tools/utils/build_tools.py
- tools/utils/dependencies.py
- Avoid linking against hdx for older USD versions.
Fixes #937
> Avoid linking against hdx for older USD versions

- render_delegate/render_delegate.cpp
- Set product metadata.
Fixes #932
I created a separate pr (same as #933) because GitHub didn't allow me to cleanly merge fix-7.0.0 to master.
> Set product metadata. (#933)

- usd_imaging/usd_lux_light_filter_adapter.cpp
This PR fixes the build of usd_imaging with USD 21.11.
Fixes #957
> Fix build of usd_imaging with USD 21.11 #957

- CMakeLists.txt
- Fixing compilation issues when using Visual Studio 2019. 
Fixes #978
> Fixing compilation issues when using Visual Studio 2019

- translator/reader/read_options.cpp
- translator/reader/reader.cpp
> Support AOV shaders on the render settings in the procedural (#968)

- procedural/main.cpp
- translator/reader/prim_reader.cpp
- translator/reader/read_geometry.cpp
- translator/reader/read_light.cpp
- translator/reader/read_options.cpp
- translator/reader/read_shader.cpp
- translator/reader/reader.cpp
- translator/reader/reader.h
- translator/reader/registry.h
- translator/reader/utils.cpp
- translator/reader/utils.h
- translator/utils/utils.h
> Remove deprecated API usage and compiler warnings in the procedural

- translator/reader/read_shader.cpp
- translator/reader/utils.cpp
- translator/reader/utils.h
- translator/writer/write_light.cpp
Fixes #1112 
std::vector<bool> does not have .data() and is represented internally as a bitfield so let's just use C arrays.
> Build fix for procedural

- translator/writer/prim_writer.cpp
- translator/writer/write_arnold_type.cpp
- translator/writer/write_camera.cpp
- translator/writer/write_geometry.cpp
- translator/writer/write_shader.cpp
- translator/writer/writer.cpp
> Fix issue setting default prim

- translator/reader/read_options.cpp
Instead of always writing the layer name to the outputs string when we read a renderSettings prim, we only set it if there are several AOVs with the same name in the same driver
Fixes #1133
> Set outputs layer names only if required #1133

- translator/reader/reader.cpp
> Build fix for OSX and linux

- render_delegate/instancer.cpp
In the render delegate, when an instancer has a velocity primvar, we now use the per-instance velocities instead of checking the variations of the instance transforms. We also do the same if the accelerations primvar is present.
This is now matching what the procedural does when it calls `UsdGeomPointInstancer::ComputeInstanceTransformsAtTimes`.
Fixes #1092
> Support per-instance velocity blur in the delegate

- translator/writer/prim_writer.cpp
When writing material bindings on shapes, we check if a material primitive is already bound, and if so we reuse it instead of creating a new one. This is allowing to reuse mayaUsd materials and add a surface/displacement shader on the arnold context
Fixes #1139
> Don't author new materials when they're already present

- SConstruct
This PR adds a build variable `MACOS_ARCH` that can be used on Mac to set it to either `x86_64`, or `arm64`, or both.
Related to #1132
> Add build variable for arm64 builds

- testsuite/test_0231/README
The fix for #1165 was missing the README for test 232
> Missing readme in test 232

- translator/reader/read_options.cpp
With this PR, we only author dataWindowNDC if the value is different from (0,0,1,1), otherwise all scenes authored from Solaris will set a region in arnold
> Only author dataWindowNDC if non-default #1161

- translator/reader/read_geometry.cpp
Fixing a build issue in the procedural after the changes done for curves pinning
> Fix build issue in the procedural

- CMakeLists.txt
- cmd/CMakeLists.txt
- ndr/CMakeLists.txt
- procedural/CMakeLists.txt
- render_delegate/CMakeLists.txt
- scene_delegate/CMakeLists.txt
- testsuite/test_0225/data/test.usda
- translator/CMakeLists.txt
- usd_imaging/CMakeLists.txt
- Organise the source files using their directory structure in Xcode and vc++
Fixes #1242
> group files with folders for vc++ or Xcode

- render_delegate/render_delegate.cpp
- handle GeometryLight in the CreateFallbackSprim function
Fixes #1251
> add GeometryLight in CreateFallbackSprim

- render_delegate/render_pass.cpp
When rendering through Solaris, the "beauty" output was provided by solaris as a Light Path Expression `C.*` for an aov named `color` . Since this lpe refers to the beauty, arnold was rendering this correctly. Unfortunately, algorithms like adaptive sampling rely on an explicit beauty aov (called `RGBA` in arnold), and since this AOV wasn't present through Solaris, adaptive sampling couldn't work. 
This PR fixes it by simply considering the beauty as arnold would expect. 
Fixes #1006
> Fix adaptive sampling in the render delegate

- ndr/parser.cpp
The  changes done in #1212 were storing output attributes with the `outputs:` namespace. Here we don't want this namespace at all, so the current PR strips out the outputs namespace from the output attribute.
> Strip outputs: prefix from output attribute in the registry

- CMakeLists.txt
- translator/writer/write_geometry.cpp
- Enable C++14
- Use primvar api instead of the mesh to create primvar
Fixes #1254
> Fixes to compile with USD 22.08

- render_delegate/shape.cpp
The issue reported in #1278 happened because 2 different settings are controlling the same attribute `instance_visibility` in the arnold instancer :
1) the eventual visibility settings done for each instance
2) the actual visibility of the proto shape (its own visibility is then set to 0, while its actual visibility goes in the instancer's `instance_visibility` array.
In the repro scene, we were trying to set 1) but this was being overridden by 2).
In this PR, as we handle 2) we also take into account the eventual per-instance visibilities and combine them into a single array value.
Fixes #1278
> Support visibility overrides on instances in the render delegate

- SConstruct
- procedural/SConscript
- New EXTRA_STATIC_LIBS variable to add static libs when compiling against static monolithic usd_m
Fixes #1289
> adds EXTRA_STATIC_LIBS variable to abuild

- procedural/SConscript
- fix a bug which prevented the static libs to be included in the link
Fixes #1296
> fix incorrect indentation

- procedural/SConscript
> add extra static libs as wholearchive on windows

- common/constant_strings.h
- ndr/utils.cpp
- render_delegate/node_graph.cpp
- render_delegate/render_delegate.cpp
- render_delegate/render_delegate.h
- render_delegate/render_pass.cpp
- translator/reader/prim_reader.cpp
- translator/reader/read_options.cpp
- usd_imaging/node_graph_adapter.cpp
* Support imager graphs in the delegate
* Read imager graphs in the reader
This attaches the imager graph to the beauty driver.
Note this will add imager nodes to the Sdr registry.
> Imagers in the delegate and the reader

- render_delegate/render_delegate.cpp
Fixes  (#1327):
* Adding a call to AiADPDisableDialogWindow() before AiBegin() in batch mode
> Ensure that the ADP dialog box will not pop up and hang the application

- testsuite/test_1315/README
- testsuite/test_1315/data/test.cpp
- translator/reader/prim_reader.cpp
- handle array primvars with constant interpolation
Fixes #1315
> handle array primvars with constant interpolation

- testsuite/test_1315/README
- testsuite/test_1315/data/test.cpp
- translator/reader/prim_reader.cpp
- convert the types with multiple components to array
Fixes #1315
> AiSceneLoad does not load array type user parameter from usd

- SConstruct
- testsuite/SConscript
- testsuite/hydra_test/renderOptions.cpp
- testsuite/hydra_test/renderer.cpp
This PR includes some changes required to run hydra_test on windows
> Fixes to run hydra_test on windows

- render_delegate/config.h
- remove one of the auto_generate_tx declaration
Fixes #1364
> remove one auto_generate_tx declaration

- render_delegate/node_graph.cpp
In the change for #1380 there's been a typo in the last commit. Fixing it
> Fix typo for #1380

- translator/reader/utils.cpp
The changes done for #1433 are not compiling with older USD versions (before 21.08), as they rely on a new API.
This PR rolls back the changes for older USD and keeps the new code for recent versions.
Fixes #1433
> Fix build issues with older versions of USD

- SConstruct
Simply turning the arnold and usd paths into absolute paths
Fixes #1471
> Support relative paths for ARNOLD and USD sdk

- README.md
- Added a note in the Limitation section of the README as we don't want to alter or force the environment variables.
Fixes #1419
> Update README with flickering issue

- CHANGELOG.md
- tools/scons-custom/site_tools/msvs.py
- tools/scons/scons-local-3.1.2/SCons/Tool/MSCommon/vc.py
This PR updates the Scons scripts, so that they can build with msvc 14.3. 
Fixes #1487
> Update scons to build with msvc 14.3

- CHANGELOG.md
A few issues, in particular on the build side, hadn't been reported in the changelog
> Add missing info to changelog

- CHANGELOG.md
- render_delegate/render_delegate.cpp
- render_delegate/render_param.h
Fixing formatting issues and outdated comments that were accidentally merged in [PR#1493](https://github.com/Autodesk/arnold-usd/pull/1493)
> Fix formatting and unused code in delegate render stats

- testsuite/SConscript
Simple change in the testsuite Sconscript, attempting to fix some issues in the CI
> Attempt to fix testsuite build issues

- CHANGELOG.md
- translator/reader/read_options.cpp
- translator/reader/reader.cpp
Adding some version checks to handle older Arnold APIs
Fixes #1519
> Fix procedural build against older versions of Arnold

- SConstruct
- plugins/ndr/SConscript
There are a few missing bits to allow compilation of the NDR plugin after the recent refactoring. 
This PR fixes them
> Fix build issues in the ndr plugin

- libs/render_delegate/reader.cpp
- remove pxr/imaging/hio/image.h
Fixes #1553
> fix compilation issue

- testsuite/test_0038/data/test.cpp
- testsuite/test_0142/data/test.cpp
- testsuite/test_0161/data/test.cpp
- testsuite/test_0162/data/test.cpp
- testsuite/test_0168/data/test.cpp
Updating the tests that call the viewport API as they were relying on the default universe, which is deprecated now
> Update tests related to viewport API

- CHANGELOG.md
- Update the changelog with the 7.2.2 changes
> Update changelog for branch fix 7.2.2

- CHANGELOG.md
Set the 7.2.2.1 version in the changelog
> Update changelog for 7.2.2.1

- libs/render_delegate/render_pass.cpp
Cosmetic change, to use existing static TfTokens
> Use static tokens for arnold:format and arnold:filter

- CHANGELOG.md
- schemas/SConscript
- Remove the schema backup optimization
Fixes #1648
> Fix schema generation

- testsuite/SConscript
- testsuite/common/testsuite.html.template
We want the testsuite report to show if we're testing in USD or in Hydra mode.
I'm also adding the version of USD in the report
> Add usd / hydra info in the testsuite reports

- CHANGELOG.md
> Merge fix-7.2.4 to master

- tools/usdgenschema/SConscript
- This removes a hack we used to compile the arnold usd procedural with a pre-package version of usd
> fix usdgenschema build on macos

- plugins/procedural/main.cpp
This PR moves a function that was previously in MtoA and MAXtoA. These plugins look for an explicit symbol in a dso that is compiled against the USD libs from MayaUSD / MaxUSD. 
The function just takes an integer as an argument, looks for the usdStage in a usdStageCache and writes to this specific usdStage (as opposed to the scene format API that writes to a usd file on disk
Fixes #1779
> Expose API function writing an arnold universe to an existing usd stage

- CHANGELOG.md
- libs/common/api_adapter.h
- libs/common/materials_utils.cpp
- libs/render_delegate/render_delegate.h
- Add the fix related to issue #1812 coming from the branch fix-7.2.5. This is the fix to optimise/limit the calls to the AiMaterialx functions
Fixes #1812
> Cherry pick + refactor fix for #1812 from branch fix-7.2.5

- libs/render_delegate/node_graph.cpp
- libs/render_delegate/render_delegate.cpp
- libs/render_delegate/render_delegate.h
- Correct missing ifdef for older versions
> Fix build with older versions of arnold

- CHANGELOG.md
- Update CHANGELOG in branch fix-7.2.5 after 7.2.5.1 release
> Update changelog for fix-7.2.5.0

- libs/render_delegate/render_delegate.cpp
> Fix compilation issue.

- CHANGELOG.md
> Update changelog after the release of 7.3.0.0 and 7.3.1.0

- CHANGELOG.md
- libs/common/constant_strings.h
- libs/render_delegate/render_delegate.cpp
> restart the render when we receive a new houdini:frame render param

- testsuite/test_0181/README
- testsuite/test_0181/data/test.usda
test 181 had to be updated in order to run in hydra mode
> Fix test_0181 in hydra mode

- libs/translator/writer/write_shader.cpp
- Restrict the imager writer code to versions superior or equal to 7.3.1
> Fix compilation issue with older versions of Arnold 

- SConstruct
- testsuite/SConscript
This simply backports the feature introduced in #2052 to https://github.com/Autodesk/arnold-usd/tree/fix-7.3.4
> Backport JUnit report from #2052 to fix-7.3.4

- libs/translator/reader/utils.cpp
The latest changes in #2111  introduced a regression with deform keys. Fixing it
> Fix regression in deform keys

- plugins/ndr/CMakeLists.txt
- plugins/usd_imaging/CMakeLists.txt
- Some cmake variables were not set, this PR just correctly sets them. The error was visible only on windows.
- I didn't update the CHANGELOG as this is a small change for the build.
Fixes #2138
> Fix cmake error " file failed to open for reading "

- CHANGELOG.md
The changes in #2143 actually fixed #1764 , so we're adding it to the changelog
Fixes #1764
> Add changelog for #1764

- plugins/procedural/SConscript
- tools/utils/dependencies.py
This PR adds support for compiling against MayaUSd builds of USD 24.11
-
> Add support for compiling against MayaUsd with USD 24.11

- SConstruct
- libs/common/SConscript
- libs/render_delegate/SConscript
- plugins/procedural/SConscript
- plugins/usd_imaging/SConscript
- schemas/SConscript
- testsuite/SConscript
- testsuite/common/testsuite.html.template
- testsuite/groups
- tools/test/__init__.py
- tools/test/__resource__/test.html.template
- tools/test/__resource__/testsuite.html.template
- tools/test/groups.py
- tools/test/test.py
- tools/test/testsuite.py
- tools/test/worker.py
- tools/usdgenschema/SConscript
- tools/utils/dependencies.py
- tools/utils/devtoolset.py
- tools/utils/misc.py
- tools/utils/system.py
This PR updates the testsuite scripts based on the ones used in other arnold projects. 
It now runs both USD and Hydra tests in a single run, showing them in the same html report.
Fixes #2172
> Improve testsuite scripts

- SConstruct
- Fixed build errors when using scons and COLOR_CMDS=1
> Fix COLOR_CMDS with SCons build

- SConstruct
- Updated CXX_STANDARD to c++17 for SCons build
> Updated CXX_STANDARD to c++17 for SCons build

- CHANGELOG.md
- libs/render_delegate/instancer.cpp
- libs/render_delegate/mesh.cpp
- Remove unnecessary allocations in mesh and instancer by making sur the VtArrays are const.
Fixes #2208
> Remove unnecessary allocations in mesh and instancer

- plugins/procedural/CMakeLists.txt
- Add the missing usdImaging dependency.
Fixes #2216
> Fix compilation of procedural hydra shared link with cmake

- libs/render_delegate/render_delegate.cpp
Yet another commit for #2234 , the last one broke compilation with older versions of USD. Adding an ifdef
> Fix compilation with older versions of USD 

- libs/render_delegate/render_delegate.cpp
> More fixes for older versions of USD

- libs/common/constant_strings.h
- libs/common/rendersettings_utils.cpp
- libs/render_delegate/config.cpp
- libs/render_delegate/config.h
- libs/render_delegate/render_delegate.cpp
- libs/render_delegate/render_delegate.h
- Exposed the html report file setting in the render settings reader / render delegate
Fixes #
> Expose the HTML report settings

- libs/common/rendersettings_utils.cpp
- libs/render_delegate/render_delegate.cpp
- Make sure the report api calls are used only in the most recent version.
> Fix api changes

- CHANGELOG.md
- README.md
- Update changelog with new versions
- Update README fix markdown linter warnings and update limitation section
> update Changelog and README.

- libs/render_delegate/reader.cpp
- libs/render_delegate/reader.h
the previous PR was missing some commits
> Add missing ifdefs for compilation against older usd

- plugins/procedural/CMakeLists.txt
- plugins/procedural/SConscript
- plugins/render_delegate/CMakeLists.txt
- With the scene index code recently added we need to link with hdsi.
> Link with hdsi scene index library

- libs/render_delegate/reader.cpp
we were just missing another ifdef for usd 22.05 and older
> Fix build issue with older versions of usd

- schemas/createSchemaFile.py
- testsuite/test_0043/data/proc.usd
- testsuite/test_0161/data/nested_proc.usda
- testsuite/test_0162/data/nested_proc.usda
- testsuite/test_0213/data/test.usda
- testsuite/test_1331/data/test.usda
- testsuite/test_1588/data/test.usda
Change the field tpye for `ArnoldUsd` `arnold:filename` to "asset"
Fixes #2326
> ARNOLD-16449 filename parameter on arnoldusd is incorrect type

- libs/render_delegate/config.cpp
- libs/render_delegate/config.h
- libs/render_delegate/render_delegate.cpp
- libs/translator/reader/read_geometry.cpp
- plugins/procedural/main.cpp
- testsuite/test_1546/data/test.ass
- use restore previous code for previous arnold versions
> Fix asset_path crash on the CI with previous Arnold versions

- CHANGELOG.md
- libs/common/constant_strings.h
- libs/render_delegate/instancer.cpp
- plugins/scene_index/CMakeLists.txt
- plugins/scene_index/SConscript
- plugins/scene_index/plugInfo.json.in
- plugins/scene_index/renderPassSIP.cpp
- plugins/scene_index/renderPassSIP.h
* render pass first implementation (modified copy from hdprman)
* support for camera visibility in the render pass
* update changelog
> Render passes scene index filter implementation (#2409)

- libs/render_delegate/render_pass.cpp
When a render settings resolution is explicitely specified, we should use that instead of the viewport returned by `HdRenderPassStateSharedPtr::GetViewport` . Since this needs to match the HdRenderBuffer resolution, we call `HdRenderBuffer::Allocate` with that resolution.
This fixes Clone rendering in Houdini Solaris
Fixes HTOA-2793
> Consider render settings resolution when provided, instead of the hydra viewport
