Autodesk/arnold-usd

- render_delegate/hdarnold.h
Don't require setting USD_1910_UPDATED_COMPOSITOR when USD is newer than 0.19.11.
- Setting USD_HAS_UPDATED_COMPOSITOR macro when USD version newer than 0.19.12.
There are no issues created for this change.
> [Render Delegate] Update hdarnold.h for 0.19.11.

- translator/reader/read_geometry.cpp
- translator/reader/read_light.cpp
- translator/reader/reader.cpp
- translator/reader/reader.h
- translator/reader/utils.cpp
- translator/reader/utils.h
Use a global UsdGeomXformCache to compute the world matrices of xformable primitives, in order to get their world matrix, instead of the local one as of today
Fixes #51
> Compute world matrix for xformable primitives #51

- README.md
- SConstruct
- docs/Doxyfile
- docs/building.md
- ndr/SConscript
- ndr/api.h
- ndr/discovery.cpp
- ndr/discovery.h
- ndr/ndrarnold.h
- ndr/parser.cpp
- ndr/parser.h
- ndr/plugInfo.json.in
- ndr/utils.cpp
- ndr/utils.h
The PR adds a Ndr Discovery and Parser plugin for arnold shaders to fix issues with the USD-0.20.02 and the UsdImagingSceneDelegate and allow users to access the shaders, their parameters and default values via a uniform API.
- Registering all the arnold shaders and setting up a filename metadata.
- Registering a filename metadata for prims.
- Updating Readme with the NDR plugin.
- Updating Readme regarding points support.
- Updating building docs with the NDR plugin.
- Fixing typos in the building docs.
- Generating the arnold_usd header for either the procedural, render delegate or ndr plugin and making all these three depend on it.
Fixes #13
> Adding an NDR plugin for arnold shaders.

- translator/reader/utils.cpp
Using the `UsdShadeMaterialBindingAPI` in the procedural instead of the removed `UsdShadeMaterial::GetBoundMaterial` when USD is at least 0.20.2.
- Using the `UsdShadeMaterialBindingAPI` in the procedural.
Fixes #59
**Additional context*
This fix requires either #42 or #57 to build since it uses `arnold_usd.h` in the procedural.
> [Procedural] Fixing build issues against USD-0.20.02.

- SConstruct
- docs/building.md
- tools/utils/build_tools.py
- Removing the USD_HAS_PYTHON_SUPPORT flag from scons and using the `pxr.h` header to decide if USD was built with python support enabled.
Fixes #5
> Removing USD_HAS_PYTHON_SUPPORT flag.

- SConstruct
- render_delegate/SConscript
- render_delegate/hdarnold.h
- tools/utils/build_tools.py
- Define `USD_HAS_UPDATED_COMPOSITOR` for USD 19.11+ instead of USD 19.12+
As far as I can tell the updated compositor API is already part of the [official 19.11 release](https://github.com/PixarAnimationStudios/USD/commit/4b1162957b2ad219e1635c81de8343be490e41fc) as described in #63. Similarly it's also in the [USD 19.11 archived release](https://github.com/PixarAnimationStudios/USD/releases/tag/v19.11)
Fixes #63
> Fix #63: Define USD_HAS_UPDATED_COMPOSITOR for USD 19.11

- procedural/main.cpp
- translator/reader/prim_reader.cpp
- translator/reader/read_light.cpp
- translator/reader/reader.cpp
- translator/reader/reader.h
- translator/reader/utils.cpp
The viewport API is randomly failing with the usd procedural. 
The issue is caused by an uninitialized variable, which this PR fixes. The variable `_convert` that was added recently wasn't initialized to `true` and because of that, the usd translation was randomly skipped.
While inspecting the code, I also fixed a possible memory leak about a `UsdArnoldReader` being allocated but not deleted at early-out. 
I also noted that when calling `AiNodeLookUpByName` we were not passing the `AtUniverse` argument to the function, which could possibly cause issues with the viewport code that relies on a non-default universe.
> Viewport callbacks not working reliably

- README.md
Add a line in `README.md` about the linux crash reported in #40
> Document linux crash in the readme

- translator/reader/reader.cpp
- translator/reader/reader.h
- translator/reader/utils.cpp
This PR is meant to address the regression about animated xforms in #80.
I see different solutions to address this issue, and I'm not totally sure which one is best :
- 1 )  every time one primitive has keys on a different frame than the current one, create one `UsdGeomXformCache` just to compute the world matrix and delete it. 
- 2 ) Create on-demand one `UsdGeomXformCache` per requested frame. The `UsdReader` would store a map of xform caches, and would create them dynamically when needed.
- 3 ) Change the time of the `UsdGeomXformCache` every time we need to get a new matrix.
///////////////////////////// 
In this commit I went for the simplest solution 1), but I'm fine with implementing a different solution if better.
3 ) would be very simple …
> Create a new Xform cache for animated xforms

- SConstruct
- cmd/SConscript
- docs/building.md
- procedural/SConscript
- render_delegate/SConscript
- schemas/SConscript
- translator/SConscript
- Adding a new USD_LIB_PREFIX flag.
- Adding example custom.py files to the documentation.
- Extending building.md about using abuild and configuring the build.
- Fixing a typo in the render delegate that turns on -fPIC on windows.
- Adding a warning about the python app shortcut on Windows 10.
- Adding dl to the dependencies when building the render delegate on Linux.
- Adding a new utility function for SCons scripts, link_usd_libraries that handles adding dependencies to builds.
Fixes #48
> Supporting building against prefixed USD libraries.

- CONTRIBUTING.md
- Update CONTRIBUTING.md to describe the preferred way to name tickets/pull requests.
Fixes #89
> Specify the preferred ticket/pull request naming behaviour in the CONTRIBUTING guide.

- render_delegate/render_delegate.cpp
Fix display settings of type int and bool on OSX.
Due to type being long long, ignore shaders, smoothing, threads, diffuse samples and more are not coming through.
Fixes #103
> Fix display settings of type int and bool on OSX

- schemas/createSchemaFile.py
- translator/writer/registry.cpp
No longer build typed schemas for shaders since we rely on `UsdShade` schemas, with the `info:id` token returning the arnold shader name.
This allows to get rid of several special cases during the schemas generation, some of which are explained in #65 
Fixes #96
**Additional c
> Don't build typed schemas for shaders

- render_delegate/mesh.cpp
- render_delegate/points.cpp
- Restarting renders when visibility is dirtied.
Fixes #95
> Re-rendering when visibility of an object changes.

- schemas/SConscript
- Raise a runtime error if `usdGenSchema` can't be found and the schema build is enabled
Fixes #105
> Raise a runtime error if usdGenSchema can't be found and the schema build is enabled.

- SConstruct
- Adding ARNOLD_BINARIES to the dynamic library path environment variable, so the linker can find symbols from libraries next to libai.
Fixes #107
> Adding ARNOLD_BINARIES to the dynamic library path to fix linking issues

- render_delegate/volume.cpp
Fix parsing of HOUDINI_PATH.  This allows the path separator to contain ; on OSX for example.
On windows the path may contain : in the path e.g. C:\plugin_path so here ; is used as the separator.  But ; may still be used on non-windows.
> Fix parsing of HOUDINI_PATH

- .gitignore
- translator/writer/prim_writer.cpp
- translator/writer/prim_writer.h
- translator/writer/registry.cpp
- translator/writer/registry.h
- translator/writer/write_geometry.cpp
- translator/writer/write_geometry.h
- translator/writer/write_light.cpp
- translator/writer/write_light.h
- translator/writer/writer.cpp
- translator/writer/writer.h
Modify the writer module so that it can convert some arnold nodes (geometries, lights), as USD builtin nodes, instead of always creating Arnold-specific schemas.
Fixes #39 
This is a first draft, that is still missing some rarely used arnold shapes (cube, sphere, cylinder), and also material bindings. We can address this in future tickets.
> Write Arnold nodes as USD builtins when possible

- render_delegate/config.h
Changing the type of progressive_min_AA_samples from bool to int.
- Changing the type of progressive_min_AA_samples from bool to int.
Fixes #131
> Changing the type of progressive_min_AA_samples from bool to int.

- translator/reader/reader.cpp
- When the reader loads the file, we are returning early if the rootLayer is nullptr.
Fixes #74
> Checking for root layer validity when loading the file.

- translator/writer/prim_writer.cpp
- translator/writer/prim_writer.h
- translator/writer/write_arnold_type.cpp
- translator/writer/write_arnold_type.h
- translator/writer/write_geometry.cpp
- translator/writer/write_light.cpp
- translator/writer/write_shader.cpp
- translator/writer/write_shader.h
- translator/writer/writer.cpp
This is an alternative solution than PR #142 in order to fix the issue #145 .
Every time we write a new node to usd, we ensure that the previous list of already exported attributes is cleared. This list is meant to avoid duplication of usd builtin parameters and arnold-namespaced parameters. But we don't need to keep a long list accumulating all the exported node. 
Since every new primitive-writer defines a function `write` and since we don't want to clear the list inside each of these functions, I'm making it so that the `UsdArnoldWriter` calls a function `primWriter->writeNode(node)` that will always clear the list before calling the virtual function `write`. To ensure that nobody calls directly `write` I'm making it protected.
In this PR I'm …
> Writer clears the list of exported attributes for every node

- testsuite/test_0014/data/scene.usda
- translator/reader/utils.cpp
- Preferring the arnold specific contexts over the default one
- Updating test 14 to fail if the old order is used
Fixes #155
> Reversing render context priority in the procedural

- SConstruct
The predefined macros, like `_GLIBCXX_USE_CXX11_ABI` should be appended to the SCons environment variable `CPPDEFINES`, not to `CCFLAGS`
> Append _GLIBCXX_USE_CXX11_ABI to CPPDEFINES instead of CCFLAGS

- procedural/main.cpp
Add the include that is needed to build scene format plugins as an experimental/unexposed API
This relates to #173 but doesn't fully address this issue, since we also need to change the version check by another test
> Add needed include for scene format plugins

- procedural/main.cpp
Set the metadata `_triggers_reload` in the procedural's attributes so that any change during IPR session clears the contents of the procedural so that they're re-generated at the next render. This is done similarly to what we have in the alembic procedural, and avoids handling this in each plugin.
In the future we'll want to be smarter, and update only what needs to be updated using the `procedural_update`  functions (see #168 ) , but for now we clear everything in order to have a correct render.
Fixes #176
> Set _triggers_reload metadata on procedural attributes

- render_delegate/mesh.cpp
- Reverting change to support `HdChangeTracker::DirtyPoints`.
- Set `vlist` in the mesh primvar loop if they are not set earlier.
Fixes #169
> Reverting change to support HdChangeTracker::DirtyPoints.

- schemas/SConscript
Fixes linkage against `tbb` when building against shared, non-monolithic USD libs using a custom `USD_LIB_PREFIX`.
Currently, if a custom prefix is passed, the `tbb` link flag gets modified as well.
> Fix tbb linkage when using a custom `USD_LIB_PREFIX`

- docs/building.md
Fix formatting and slightly reorganise the build instructions.
Fixes #194
> Reformat building instructions

- translator/writer/prim_writer.cpp
- translator/writer/prim_writer.h
- translator/writer/write_geometry.cpp
- translator/writer/writer.cpp
- translator/writer/writer.h
The usd writer now exports arnold shader assignments by connecting a `UsdShadeMaterial` primitive, on which both the surface shader and displacement are linked.
Since the material node doesn't exist in the arnold scene, we need to give it a unique name. Here I'm appending both the name of the surface shader and the eventual displacement, so that every combination surface + displacement is unique, and so that we share the same material between geometries.
While doing it, I saw that we were sometimes doing the export of a node multiple times uselessly (in case of shader links or node connections), so I've enforced it here. The list of exported attributes was also cleared by mistake when setting connections, this is now fixed.
I am not handling the …
> Export material bindings in the writer

- translator/reader/prim_reader.cpp
- translator/writer/prim_writer.cpp
The USD writer was never saving AI_TYPE_NODE attributes. When exporting to usd, we check if the attribute values are equal to default or not, to decide if we want to author these attributes in the usd file.
The test for node attributes being default was incorrect, because of a typo. We were testing that the value was *not* null instead of testing that it's null.
While checking the code, I also realized that the reader always appends a "/" at the beginning of a  name, in the case of node attributes, which won't work if the node name already starts with "/".
Fixes #190
> Ensure attributes of type "node" are converted by the writer

- translator/reader/reader.cpp
- translator/reader/reader.h
This PR is needed to support point instancer properly in #153 
Before creating a node, we check if it already exists by calling `AiNodeLookUpbyName`. If it exists, we skip its creation as it's already there. But this arnold function can actually return us a node with the same name in the scope of a parent procedural. So if the usd procedural is created by another procedural and the parent has a node with the same name, there will be a confusion between both and some nodes won't be generated.
Note that when #179 is pushed we'll no longer need this test in `UsdArnoldPrimReader::createArnoldNode` as we won't need to check if a node already exists anymore, before creating it.
Also, there are still some places in the core where we still call …
> Reader checks existing node's parent before skipping its creation

- procedural/main.cpp
- translator/utils/utils.h
Take into account `options.procedural_search_path` , similarly to what the alembic procedural already does. We check this attribute, and try to see if the filename exists on disk relatively to one of these search folders.
I'm not sure how's the best way to test this, since all the paths are already relative to the testsuite folder. But I've tried it locally and it works, for both the render and the viewport api in maya
Fixes #182
> Consider option's procedural search path

- testsuite/groups
Related to #196  , with the Arnold CI we noticed that the kitchen scene in `test_0016` was also giving random results with a single thread. I thought the issues only happened in parallel translation, but it was just more frequent.
We need to disable this test until the issue is properly solved
> Disable the kitchen scene test again

- translator/writer/prim_writer.cpp
- translator/writer/writer.cpp
Instead of using `AiNodeGetName` for node / node-array attributes, use `UsdArnoldPrimWriter::getArnoldNodeName` that does some formatting to sanitize the names
Fixes #208
> Writer sets proper names for node attributes

- schemas/createSchemaFile.py
Ensure we're not creating a token called `linux` (for attribute `string_replace.os` )
Fixes #219
> Fix build issue regarding schemas on linux

- render_delegate/utils.cpp
- Fixing typo in the parameter conversion for the render delegate.
Fixes #236
> Fixing typo in the parameter conversion for the render delegate.

- testsuite/test_0009/data/sphere.usd
- translator/reader/prim_reader.cpp
- translator/reader/prim_reader.h
- translator/reader/read_geometry.cpp
- translator/reader/read_light.cpp
We used to set `vtValues` by assuming they had the exact type that is expected. But the render delegate code is testing which value type an attribute is holding before setting it. For example an integer attribute can either be defined as `int` or as `long`, etc...
For the issue reported in #238 , boolean attributes can sometimes be defined as an `int` so we're also treating this use case.
I changed `test_0009` to have a boolean attribute expressed as an integer. With the proposed commit it passes successfully.
Fixes #238
> Check which type is holding a vtValue before setting attributes 

- render_delegate/render_buffer.cpp
- render_delegate/render_buffer.h
Fix pixel format mismatch when copying to hyrda render buffers, and fix flash in screen and crash when creating render settings node on OSX.
The performance is slower after adding the render settings node due the per pixel copying.   It would preferable to use buffers in the render delegate that match the hydra buffers - see #8.
> Fix pixel format for render buffer conversion (#245)

- render_delegate/light.cpp
- Dirtying the Transform when Params are dirty for light updates.
Fixes #243
> Dirtying the Transform when Params are dirty for light updates.

- procedural/main.cpp
- Changing RTLD_GLOBAL to RTLD_LOCAL when loading the procedural for offsetting unloading at Arnold shutdown.
Related to Arnold core ticket 9459.
> Changing RTLD_GLOBAL to RTLD_LOCAL in procedural main

- docs/building.md
- render_delegate/light.cpp
- render_delegate/mesh.cpp
- render_delegate/mesh.h
- render_delegate/render_delegate.cpp
- render_delegate/utils.cpp
- render_delegate/utils.h
- Adding support for computed primvars
Fixes #265 
I raised the minimum required USD version to 19.05 since some of the ext computation utils are named differently in previous versions. Katana 3.2 uses 19.05 and Houdini ships 19.11, so it's reasonable to bump up the version requirement.
> Adding support for computed primvars

- render_delegate/light.cpp
- render_delegate/material.cpp
- render_delegate/mesh.cpp
- render_delegate/points.cpp
- render_delegate/render_delegate.cpp
- render_delegate/render_param.cpp
- render_delegate/render_param.h
- render_delegate/render_pass.cpp
- render_delegate/shape.cpp
- render_delegate/volume.cpp
- Improving render API usage.
- Using `AiRenderInterrupt` instead of `AiRenderAbort`.
- Not using `AiRenderEnd` anymore.
- Removed `HdArnoldRenderParam::Restart`.
- Renamed `HdArnoldRenderParam::End` to `HdArnoldRenderParam::Interrupt` to better reflect what the function is doing.
Fixes #270
> Improving render API usage.

- procedural/main.cpp
- translator/writer/writer.cpp
- translator/writer/writer.h
Adding a parameter "mask" on the USD writer. It will determine over which type of arnold nodes we loop when converting the scene to usd.
The scene format writer function looks for a parameter `mask` from the `AtParamValue` argument, and eventually sets it in the writer before running the conversion
Fixes #274
> Add mask parameter to the usd writer 

- procedural/main.cpp
- translator/reader/reader.cpp
- translator/reader/reader.h
- translator/reader/registry.cpp
- translator/reader/registry.h
We're adding a parameter `mask` to the reader in order to filter the type of nodes that are exported from usd to arnold. We use this mask to prevent options, filters, drivers, etc... to be created when loading a usd file through a procedural. This way we're consistent with .ass procedurals 
This is an enhancement since we provide a new feature, but it's also a bugfix because the current behaviour is causing crashes in the arnold plugins.
Fixes #276
> Add mask to the usd reader

- render_delegate/render_param.cpp
- render_delegate/render_param.h
- Introduced a new variable on `HdArnoldRenderParam` that can be used to store dirtying information outside using the Arnold API functions.
Fixes #270.
> Forcing renders to restart if the scene was dirtied after converging

- translator/reader/read_shader.cpp
There were some typos in the reader when loading a `UsdPreviewSurface`. Some empty spaces around the " specular_IOR " attribute name, and we were setting the opacity as a float instead of RGB.
Fixes #284
> Fix warnings with UsdPreviewSurface in the procedural

- translator/reader/reader.cpp
We were using `s_readerRegistry` which is null when called by the viewport API `procedural_viewport`.
We should simply be using `_registry` that is tested and set properly.
Fixes #295
> Fix crash in the viewport functions #295

- procedural/main.cpp
- translator/reader/reader.cpp
When trying to write to a USD file with upper-case extensions, we convert it to lower case to prevent the crashes
Fixes #288
> Prevent crashes when writing USD files with upper-case extensions

- SConstruct
- render_delegate/render_delegate.cpp
- render_delegate/render_delegate.h
- render_delegate/render_pass.h
Remove arnold:global: prefix (see #302) due to namespacing of render settings parameters.
> Remove arnold:global: prefix (#302)

- translator/writer/prim_writer.cpp
Simply adding the code needed for closure attributes. Now writing closure attributes is no longer failing, and the resulting usd file can be read properly and resaving to .ass does a proper roundtrip
Fixes #322
> Support writing closure attributes to USD

- translator/reader/prim_reader.cpp
- translator/reader/utils.cpp
- translator/reader/utils.h
- translator/writer/registry.cpp
- translator/writer/write_options.cpp
- translator/writer/write_options.h
The problem is twofold :
1 - in the USD writer, we need a special treatment to translate `options.outputs` to USD. The problem is that the usd primitive names are different from the arnold node names, and `options.outputs` is a string array that contains the name of driver and filter nodes. Therefore we need to modify this strings so that the node names correspond to the usd ones
2 - In the USD reader, the string array attributes weren't translated properly. Given how the code was written, we were trying to read a string array attribute as a TfToken array, which fails. Plus, later on we were trying to do a memcopy of `TfToken` to `AtString` which obviously cannot work. So we need to do a special treatment for string array attributes (like we …
> Translate the options node properly

- translator/reader/utils.cpp
In #321 we introduced a function `exportStringArray` but some things are missing.
The function is supposed to return a value (the size of the array), but it wasn't actually returning it.
Also, it's better to test if each string is empty or not, because the behaviour of `AtString(nullptr)` might not be reliable.
> Fixes in exportStringArray function

- testsuite/groups
This  commit is related to #26 , 
we're temporarily disabling the test running `arnold_to_usd` test_0040, because it should only be executed when `BUILD_USD_WRITER=True`.
> Temporarily disable test_0040

- translator/writer/prim_writer.cpp
We ensure we're not calling a function pointer that is empty, for pointer attributes like `procedural_user_ptr`. For now we're still not translating pointer attributes, which are not widely used.
Fixes #342
> Don't crash when trying to write pointer attributes

- translator/reader/reader.cpp
- translator/reader/utils.cpp
When the reader is called without any parent procedural (thus from the scene format loader), we look for the render camera to get the shutter range. This will tell us how to load the USD data.
While doing the change, I noticed that before we were adding an additional useless time sample when the arnold data had only 2 motion keys (which is the default use case), so I've also fixed this 
Fixes #346
> Support motion blur in the scene format loader

- translator/reader/utils.h
- translator/writer/prim_writer.cpp
This PR ensures that we're writing each of the motion keys from arnold array attributes, whether they're saved as USD builtin attributes (mesh matrix, vertices, etc...) or whether they're saved as arnold-specific attributes.
I also fixed another issue related to the amount of keys saved like in #347 , in another part of the reader code.
Fixes #334
> Support motion keys in the USD writer

- translator/writer/prim_writer.cpp
When a per-channel connection is found in an arnold scene, we insert a `float_to_rgba` shader in the shading tree. It gets connected to the input attribute, and we can set each of its channels independantly. Note that arnold handles the eventual different types in the connection so always using this RGBA shader works, even for RGB, Vector, Vector2.
Fixes #351
> Write per-channel connections by inserting adapter shaders

- translator/writer/write_geometry.cpp
In this PR we're ensuring that we always write `polymesh.subdiv_iterations` when writing a usd file.
Usually, an attribute gets written if and only if the value is different from the default (for arnold), but this no longer works if the default in USD is different from the default in arnold.
This will need a test in #157 
Fixes #349
> Always write polymesh.subdiv_iterations

- translator/writer/prim_writer.cpp
This looks like an optimization in arnold matrices. Even though the array isn't empty, it's contents are empty, so what's returned by `AiArrayMap` can be null. This PR is just about doing this check.
Fixes #360
> Fix crash in the writer with empty arrays

- translator/writer/prim_writer.h
- translator/writer/registry.cpp
- translator/writer/write_arnold_type.cpp
- translator/writer/write_arnold_type.h
We register a new primitive writer for `ginstance` nodes.
It will do a special treatment for attributes `visiblity`, `sidedness`, `matte`, `receive_shadows`, `self_shadows`, `invert_normals`. Note that we don't consider `opaque` which is not used anymore.
For these attributes, we compare the value with the value from the instanced node. If the value is different, we author them. 
Fixes #362
> Improve how ginstance attributes are written

- translator/reader/read_light.cpp
We just need mesh lights reader to call the function that was introduced in #340 for skydome and quad lights.
I have a test scene ready, but it requires the scene format testsuite first. Loading mesh lights through a procedural doesn't seem to work in arnold, so I cannot test it with the procedural
Fixes #365
> Support textured mesh lights

- translator/writer/prim_writer.cpp
- translator/writer/prim_writer.h
- translator/writer/write_geometry.cpp
- translator/writer/writer.cpp
- translator/writer/writer.h
Instead of looking for `motion_start`, `motion_end` every time we write an animated attribute, we now store this value at first when each primitive gets written. If the attribute isn't found, we default to the camera shutter start / end, which itself is stored in the main `UsdArnoldWriter` before the iteration starts.
When #157 is implemented, we can add a test for this use case, with an animated projection (using `uv_projection` and `matrix_interpolate`)
Fixes #368
> Ensure motion range is written properly

- translator/writer/registry.cpp
- translator/writer/write_shader.cpp
- translator/writer/write_shader.h
We're adding a writer for toon shader. In addition to the regular shader export, it will do modify the attributes `rim_light` and `lights` so that these strings match the nodes names in the usd scene.
The attribute `lights` is slightly more complicated, as there can be multiple light names concatenated.
MtoA's test 273 is a good candidate when #157 will be implemented
Fixes #374
> Add a writer for toon shader

- translator/reader/prim_reader.cpp
We load primvars from a usd primitive, even when they have a custom namespace.
Only primvars namespaced by `arnold:` are ignored because they're treated separately.
Fixes #382
> Load namespaced primvars

- translator/writer/prim_writer.cpp
- translator/writer/writer.cpp
When writing to usd an arnold node with an empty name, we give it an arbitrary name to prevent the crashes.
Here we put them under a group "unnamed" and another with the node type. Then the final name will be based on the AtNode pointer. So for example, a standard_surface shader without any name will be named in usd as `unnamed/standard_surface/p000001734935B0F0`.
Note that the pointer string must be prefixed with "p" otherwise USD will complain if it starts with the digit.
Also, for the explanation, the actual crash was in fact caused by `_exportedNodes.insert(nodeName) where we try to insert an empty string in an unordered_set. Asking usd to create a node with an empty name caused a usd error but didn't crash. 
**Issues fixed in this pull …
> Prevent crashes when writing nodes with empty names

- translator/CMakeLists.txt
- translator/reader/read_camera.cpp
- translator/reader/read_camera.h
- translator/reader/read_geometry.cpp
- translator/reader/reader.cpp
- translator/reader/registry.cpp
- translator/writer/prim_writer.cpp
- translator/writer/registry.cpp
- translator/writer/write_camera.cpp
- translator/writer/write_camera.h
- translator/writer/write_shader.cpp
- translator/writer/write_shader.h
- translator/writer/writer.cpp
Instead of writing arnold cameras as `ArnoldPerspCamera`, `ArnoldOrthoCamera` schemas, we now write them as `UsdGeomCamera` primitives.
Since there are some formulas when converting arnold's `fov` to USD horizontal and vertical aperture + focal length, I'm writing both the usd native parameters, and also the arnold one as an arnold primvar `primvars:arnold:fov`. 
Same in the reader : we first read the usd builtin attributes, but if a primvar is present, then its value will be used.
This will require a test when #157 is done, as we can't really test this through a procedural
Fixes #345
> Support UsdGeomCamera in the translator

- render_delegate/render_buffer.cpp
- Not unlocking the render buffer in Unmap when the buffer is empty.
Fixes #394
This was a different behavior between Houdini and Usdview I believe. In Hydra and usdview, when `HdRenderBuffer::Map` returns a nullptr, `HdRenderBuffer::Unmap` is not used. Our implementation relied on this behavior, even though this was not hinted at in the HdRenderBuffer base class. In Houdini, this lead to calling `HdRenderBuffer::Unmap` on empty buffers, calling `std::mutex::unlock` on non-locked mutexes. This is an undefined behavior in the standard (`The mutex must be locked by the current thread of execution, otherwise, the behavior is undefined.`), but it was not causing an issue on non-windows …
> Not unlocking the render buffer in Unmap when the buffer is empty.

- render_delegate/render_delegate.cpp
Fixes #398, since windows is receiving the boolean value as long long
> Check for long long type in _CheckForBoolValue (#398)

- procedural/CMakeLists.txt
- procedural/SConscript
- procedural/macos_export_list
- procedural/macos_export_list_no_scene
- procedural/plugin.map
- Limiting symbol export of procedural on Linux and OSX.
Fixes #409
> Limiting symbol export of procedural on Linux and OSX

- procedural/SConscript
- tools/utils/dependencies.py
- translator/CMakeLists.txt
- translator/SConscript
- Adding usdSkel as a link time dependency when using a shared USD build.
#329
This was missing from pull request #419 and I didn't test building against a shared usd build
> Adding usdSkel as a link time dependency when using a shared USD build

- render_delegate/render_param.cpp
- render_delegate/render_param.h
- render_delegate/render_pass.cpp
- Resetting the aborted status when the scene changed.
Fixes #430
The render delegate stored an `aborted` flag, that stopped it from restarting renders when the render returned with an error. However, this `aborted` flag was never reset when there was a significant change to the scene (that could have fixed the previous issue). I introduced a new flag, `clearStatus` to `HdArnoldRenderParam::Interrupt`, with a default value of true. In most cases we want to clear the aborted flag, except when camera changes in the render pass, or the fallback buffers are used, because we know that these changes won't affect the status of renders.
One of the most obvious use cases was when the user enters …
> Resetting the aborted status when the scene changed.

- translator/reader/read_geometry.cpp
- translator/reader/read_geometry.h
- translator/reader/registry.cpp
This ticket improves the work done in #424 and now allows for recursive nested procedurals.
Now we create a procedural in a temporary universe, and we call `AiProceduralViewport` in this procedural, so that it populates the desired universe. If another usd procedural is found, the same will happen recursively, and so on....
Fixes #435
> Extend viewport representation of nested procedurals

- render_delegate/render_delegate.cpp
- Interrupting renders when destroying a Bprim.
Fixes #439
> Interrupting renders when destroying a Bprim

- render_delegate/constant_strings.h
- render_delegate/material.cpp
- Using the sub-network connected to a preview surface's displacement parameter when preview surface used as displacement.
Fixes #448
> Using the sub-network connected to a preview surface's displacement parameter when preview surface used as displacement

- render_delegate/utils.cpp
- render_delegate/utils.h
- testsuite/CMakeLists.txt
- testsuite/groups
- testsuite/test_0134/README
- testsuite/test_0134/data/test.cpp
- std::string and TfToken is supported when reading in constant primvars
- When using HdArnoldSetParameter, we are also checking for Arrays with at least one compatible element.
- When setting constant primvars, we treat single element arrays as single values
- Adding test_0134 to test the new behavior of `HdArnoldSetParameter`, `HdArnoldSetConstantPrimvar` and `ConvertPrimvarToBuiltinParameter`.
Fixes #456
> Using single element arrays to set parameters

- cmake/modules/FindUSD.cmake
- docs/building.md
- procedural/SConscript
- tools/utils/dependencies.py
- translator/CMakeLists.txt
- translator/SConscript
- Adding documentation for building for USD 20.05 and Houdini 18.0 on Linux.
- Adding missing bits to link against UsdRender when using a shared USD build.
Fixes #71
#453
> Adding documentation for building for USD 20.05 and Houdini 18.0 on Linux

- render_delegate/render_pass.cpp
- render_delegate/render_pass.h
- Allow users to overwrite the default filter and use it for any rendervar without a filter.
Fixes #475
> Allow users to overwrite the default filter and use it for any rendervar without a filter

- render_delegate/renderer_plugin.cpp
- render_delegate/renderer_plugin.h
- Implementing alternative HdRenderDelegate::CreateRenderDelegate(const HdRenderSettingsMap& settingsMap)
Fixes #488
> Implementing alternative HdRenderDelegate::CreateRenderDelegate function override

- render_delegate/basis_curves.cpp
- Using modff instead of modf to avoid bad type deduction with GCC 4.8.5. 
Fixes #501
> Using modff instead of modf in basis_curves

- translator/reader/read_geometry.cpp
We were just missing a call to `ReadMatrix` in `UsdArnoldReadGenericPoints::Read` , that is used for the viewport API in points mode
Fixes #513
> Viewport representation in points mode now reads the matrix

- render_delegate/constant_strings.h
- render_delegate/instancer.cpp
- render_delegate/material.cpp
- render_delegate/mesh.cpp
- render_delegate/mesh.h
- render_delegate/render_pass.cpp
- render_delegate/utils.cpp
- render_delegate/utils.h
- testsuite/test_0036/data/scene.usda
- Adding per-face material assignment support to the Render Delegate.
- Ran clang-format on render_delegate.
- Removed the disp_map primvar from test_0036, test 36 is testing material assignments via GeomSubsets, so it shouldn't be there.
Fixes #29
> Adding per-face material assignment support to the Render Delegate.

- procedural/main.cpp
- translator/reader/read_geometry.cpp
- translator/writer/prim_writer.cpp
- translator/writer/prim_writer.h
- translator/writer/write_arnold_type.cpp
- translator/writer/write_camera.cpp
- translator/writer/write_geometry.cpp
- translator/writer/write_light.cpp
- translator/writer/write_shader.cpp
- translator/writer/writer.h
In this PR, it's possible to give the Usd writer a "scope" string. This scope will be added as a prefix to all the usd primitive names to create.
I have tested the feature relying on MtoA's call to `AiSceneWrite` with this new param map value, but I still need to find a way to test this in the testsuite.
Fixes #292
> Support scope in the USD writer

- procedural/main.cpp
- testsuite/test_0138/README
- testsuite/test_0138/data/scene.ass
- testsuite/test_0138/data/test.cpp
- translator/writer/prim_writer.cpp
In #522 we implemented a scope for the USD writer. However there were a few issues that are addressed in this PR:
- Calling `scene_write` with an empty `params` was crashing
- Materials were written as `/materials/{scope}/{material_name}`,  they should instead be written as `/{scope}/materials/{material_name}`
- Even with a scope in the usd file, we were saving the attributes `name` of the original arnold name, and this name was restored when converting back the scene to arnold. This could have ended up causing name clashes, so we're no longer saving the original arnold name when a scope is used.
- We were missing a test, that I added as `test_0138`
Fixes #292
> More fixes, and test for the export scope

- translator/writer/write_geometry.cpp
The usd reader will read either "uv" or "st" primvars as being the native uv coordinates of the mesh. 
So the usd writer could write to either one or the other without causing any major change.
This PR writes them as "st" for the reasons described in #542 , I verified that the whole testsuite still passes correctly, and that all tests that resave a file do save the coordinates as "st".
I'm not sure of how to test this, since both will end up being read the same way by the usd reader. Maybe the important test is to verify that the roundtrip works well, which is what lots of existing tests are doing.
Fixes #542
> Write UV coordinates as primvars:st

- SConstruct
This was breaking linux builds, since clang was not found.
- Revert to original Environment creation
- MSVC_VERSION is declared only in windows
Fixes #549
> Restores SCons Environment creation and adds MSVC_VERSION only in windows

- SConstruct
We don't need to install the License.md file if  PREFIX is left to its default value, as we'd be installing it in its own folder.
This PR installs the license only if we're choosing a specific installation folder
Fixes #553
> Fix compilation error with License.md 

- render_delegate/material.cpp
- render_delegate/material.h
- Removing override from HdArnoldMaterial::Reload.
Fixes #567
> Removing override from HdArnoldMaterial::Reload

- render_delegate/basis_curves.cpp
- Removing unnecessary widths query from HdArnoldBasisCurves::sync.
Fixes #574
> Removing unnecessary widths query from HdArnoldBasisCurves::sync

- render_delegate/utils.cpp
- testsuite/groups
- testsuite/test_0134/data/test.cpp
- testsuite/test_0146/README
- testsuite/test_0146/data/test.cpp
- Support SdfAssetPath in _DeclareAndAssignConstant.
- Converting to AtArray<AtString> from VtArray<std::string>, VtArray<TfToken> and VtArray<SdfAssetPath>.
- Adding test_0146 to test the new string conversion functions.
- Check for below zero indices when writing point instancer user data.
Fixes #481
> Adding support for converting VtArray/String Types to user data

- render_delegate/constant_strings.h
- render_delegate/utils.cpp
- Add support for autobump visibility.
- Ignore subsurface ray types sets
Fixes #597
> Add support for autobump visibility and ignore subsurface ray types

- testsuite/test_0148/README
- testsuite/test_0148/data/scene.ass
- testsuite/test_0148/data/test.cpp
- translator/writer/write_geometry.cpp
When writing to USD, if a polymesh has an empty `nsides` array, we consider that all polygons are triangles as arnold does.
This way, we ensure that other USD tools will understand such geometries
Fixes #596
> Support polymeshes with empty nsides array

- cmake/modules/FindArnold.cmake
- Fixing parsing of ARNOLD_VERSION_FIX when multiple groups of numbers are matched.
Fixes #624
> Fixing parsing of ARNOLD_VERSION_FIX when multiple groups of numbers are matched

- schemas/createSchemaFile.py
- translator/reader/prim_reader.cpp
- translator/reader/prim_reader.h
- translator/reader/read_arnold_type.cpp
- translator/reader/reader.cpp
- translator/writer/write_arnold_type.cpp
In order to address #583 , we need to add an `arnold:` namespace to all the attributes from arnold schemas.
This PR handles this in the writer, reader and the schemas generation code.
In order to be backwards compatible, the reader needs to add a special case in a couple of places. 
Note that I could have made this case more "generic", by adding a list of allowed namespaces in `_ReadArnoldParameters` instead of an additional flag.
But after trying it, I felt like it made the whole code more complicated, and possibly less efficient, for a very special use case that should probably be removed after a couple of versions. So the optional boolean argument seemed less intrusive to me.
I verified that the testsuite passes, and it also passes if I remove …
> Namespace arnold schemas params with arnold

- translator/writer/write_arnold_type.cpp
- translator/writer/write_camera.cpp
- translator/writer/write_geometry.cpp
- translator/writer/write_light.cpp
- translator/writer/writer.cpp
- translator/writer/writer.h
**Changes proposed in this pull request** 
Before authoring a new xformable prim, we now create all the parent prims as xforms instead of letting them be created implicitely by USD as non-typed prims.
Fixes #629
> Create hierarchy with xform primitives in the writer

- render_delegate/constant_strings.h
- render_delegate/utils.cpp
- Setting motion_start and motion_end when applying transformation matrices.
Fixes #638
> Setting motion_start and motion_end when applying transformation matrices

- translator/reader/reader.cpp
When the procedural `object_path` points at a root primitive that is not active, we just throw a warning instead of an error.
We still dump an error if the object path doesn't match any primitive in the usd stage
Fixes #643
> Only dump a warning if root prim is not active

- render_delegate/light.cpp
- render_delegate/render_delegate.cpp
- render_delegate/shape.cpp
- Added several render interruptions that were missing previously. Generally, their lack didn't cause any issues, because we were already in an interrupted state, but this way we better match the logic of the other sync functions.
- Fixed a bug when a shape was not affected by any light or shadow.
#412
> Improving light linking code and fixing a bug

- render_delegate/light.cpp
- Removing #if from TF_DEFINE_PRIVATE_TOKENS.
Fixes #663
> Removing #if from TF_DEFINE_PRIVATE_TOKENS

- render_delegate/basis_curves.cpp
- render_delegate/mesh.cpp
- render_delegate/points.cpp
- Converting HdInterpolationVarying primvars to vertex user data.
Fixes #667
> Converting HdInterpolationVarying primvars to vertex user data.

- translator/reader/reader.cpp
When the usdStage comes for the stage cache with a given cache ID, we should not modify it.
Therefore we skip the call to `UsdSkelBakeSkinning` that is meant to apply the skinning on the whole scene, 
and thus modify it.
Fixes #683
> Don't apply skinning if a cache ID  is set 

- testsuite/test_0166/data/test.ass
Test 166, added for #697 had `abort_on_license_fail on`. This will prevent the test from succeeding if no valid license is found
> Fixing test 166

- SConstruct
In this PR I'm removing the dependency between the testsuite and the procedural (which is what I've been doing locally for months, to avoid the issues described in #746)
In order to be consistent, I'm also doing the same with the render delegate and the ndr plugins.
Fixes #746
> Remove the dependency between the testsuite and the procedural

- common/constant_strings.h
- common/shape_utils.cpp
- common/shape_utils.h
- render_delegate/native_rprim.cpp
- render_delegate/render_delegate.cpp
- usd_imaging/shape_adapter.cpp
- usd_imaging/shape_adapter.h
- usd_imaging/shape_adapters.cpp.in
- Simplify accessing Arnold parameters using UsdImagingPrimAdater::Get.
Fixes #743
> Simplify accessing Arnold parameters using UsdImagingPrimAdater::Get.

- translator/reader/reader.cpp
As a complement to #734 , we're now only setting the id on shapes if the reader has a parent procedural.
This way, when we're using the scene format to convert from usd to arnold scenes, we're not forcing the id to be 0.
> Only force the ID to shapes if the reader has a parent procedural

- render_delegate/CMakeLists.txt
- render_delegate/SConscript
- render_delegate/basis_curves.cpp
- render_delegate/material.cpp
- render_delegate/material.h
- render_delegate/material_tracker.cpp
- render_delegate/material_tracker.h
- render_delegate/mesh.cpp
- render_delegate/native_rprim.cpp
- render_delegate/points.cpp
- render_delegate/render_delegate.cpp
- render_delegate/render_delegate.h
- render_delegate/rprim.h
- render_delegate/volume.cpp
- render_delegate/volume.h
- Tracking material assignments to shapes and resyncing material IDs if terminals have changed.
Fixes #751
> Tracking material assignments to shapes and resyncing material IDs if terminals have changed

- render_delegate/instancer.cpp
- Removing the NeedsUpdate check when setting primvars on the Point Instancer
Fixes #759
The HdArnoldPrimvar::NeedsUpdate function's purpose is to avoid setting the same primvar multiple times on a shape when it didn't change between sync function calls. While this works well for all the primitives, the Point Instancer is an exception. Here, we run the primvar conversion loop several times, and calling `NeedsUpdate` will remove the dirty call the first loop (which is non-sequential, so happens randomly), so when we are calling the loop for the second time, all the primvars will be ignored.
This syncing behavior happens due to how Hydra handles instancers compared to USD. In Hydra, we …
> Removing NeedsUpdate check when setting primvars on the Point Instancer

- translator/writer/write_arnold_type.cpp
- translator/writer/write_geometry.cpp
We don't do things differently for arnold schemas as compared to builtin schemas during the writer process.
Note that the writer itself already ensures that we don't go twice through the same node, so this test wasn't actually needed.
This is allowing me to extend maya-usd export to handle arnold custom schemas, and could probably be used in the future as well to append multiple frames to a single usd file.
Fixes #768
> Write custom primitives even when they already exist

- render_delegate/native_rprim.h
- render_delegate/render_pass.cpp
Remove override for GetBuiltinPrimvarNames and fix another unrelated warning for int cast.
> Fix build issue with Houdini 18.0 (#792)

- render_delegate/render_pass.cpp
- Interrupting the render before deleting nodes in HdArnoldRenderPass.
Fixes #797
> Interrupting renders before deleting render pass nodes.

- render_delegate/utils.cpp
- testsuite/test_0134/data/test.cpp
- Converting string/token/asset path primvar arrays to built-in string arrays.
- Updating test 134 to cover the new functionality.
Fixes #808
> Converting string/token/asset path primvar arrays to built-in string arrays

- render_delegate/render_delegate.cpp
- render_delegate/render_delegate.h
- Passing `AI_SESSION_INTERACTIVE` to `AiRenderSession` when creating a new render session.
- Renaming `_render_session` to `_renderSession` on `HdArnoldRenderdelegate` to match the naming conventions.
Fixes #821
> Passing AI_SESSION_INTERACTIVE when creating AiRenderSession

- procedural/main.cpp
- Using AiResolveFilePath when opening files in the procedural.
Fixes #818
> Using AiResolveFilePath when opening files in the procedural

- CMakeLists.txt
- cmake/utils/options.cmake
- Adding BUILD_BOOST_ALL_NO_LIB to the cmake configuration.
Fixes #828
> Adding BUILD_BOOST_ALL_NO_LIB to the cmake configuration

- render_delegate/native_rprim.h
- Adding override decorator for GetBuiltinPrimvarNames if PXR_VERSION >= 2002.
Fixes #830
> Adding override decorator for GetBuiltinPrimvarNames if PXR_VERSION >= 2002

- render_delegate/basis_curves.cpp
- render_delegate/hdarnold.h
- render_delegate/mesh.cpp
- render_delegate/native_rprim.h
- render_delegate/points.cpp
- render_delegate/points.h
- render_delegate/render_buffer.cpp
- render_delegate/render_buffer.h
- render_delegate/render_delegate.cpp
- render_delegate/render_delegate.h
- render_delegate/render_param.cpp
- render_delegate/render_param.h
- render_delegate/render_pass.cpp
- render_delegate/rprim.h
- render_delegate/utils.cpp
- render_delegate/utils.h
- Adding velocity and acceleration based interpolation to points.
- removing `USD_HAS_UPDATED_TIME_SAMPLE_ARRAY` from hdarnold.h.
- Adding a new `HdArnoldUnboxSample` to simplify dealing with hydra primvar samples.
Fixes #832
The pr contains work for #673
> Adding velocity and acceleration based interpolation to points and removing USD_HAS_UPDATED_TIME_SAMPLE_ARRAY from hdarnold.h (#673)

- common/constant_strings.h
- testsuite/test_0045/data/test.cpp
- Adding missing deformKeys and houdiniFps defines to constant_strings.
- Including common_utils in test_0045 and adding a new test for ArnoldUsdMakeCamelCase.
These are changes missing from #833 and I noticed a build error with test_0045.
> Adding missing defines to constant_strings.h and fixing test_0045/data/test.cpp.

- procedural/main.cpp
This PR sets the universe explicitely in `AiUniverseGetCamera` for motion settings, instead of relying on the default universe.
I also found a similar issue when getting the current frame of the universe, during `scene_load`
Fixes #847
> Consider the corrent render camera for motion settings

- render_delegate/nodes/driver_main.cpp
- render_delegate/nodes/nodes.h
- render_delegate/render_pass.cpp
- Avoid updating the main driver matrices in case of camera movement.
Fixes #869
> Avoid updating the main driver matrices in case of camera movement

- render_delegate/render_delegate.cpp
- Changing the fallback shader to standard surface.
Fixes #861
Forcing the fallback shader on the ALAB scene.
Using the current utility shader:
After the PR:
We might want to wait until #462 is fixed, so in case of no lighting in the scene, we can still see something.
> Changing the fallback shader to standard surface.

- translator/writer/prim_writer.cpp
- translator/writer/writer.h
When appending matrix attributes to existing usd files, if no value was previously authored, it means that it was originally equal to identity matrix. In that case we ensure that a default value is set before calling `writer.SetAttribute`.
In this later function, we also ensure that we set the attribute value if no value had been previously authored.
Fixes #871
> Enforce writing multiple frames when no default is authored

- testsuite/test_0015/data/scene.usda
- testsuite/test_0140/data/test.usda
- testsuite/test_0181/data/test.usda
- translator/reader/read_light.cpp
- Supporting both new and old light parameter naming conventions, without using the UsdLux APIs.
- Changing tests 140 and 181, so we make sure the new parameters are preferred over the old ones.
- Fixing test 15 with 21.08.
- Adding support for animated color temperature.
Fixes #880
Fixes #772
I benchmarked the new code vs the old code, using the worst possible case: when no parameters are set we are checking both the new and old parameter names. The results were: 1-3 seconds when translating 1 million UsdLux lights to Arnold primitives on a single thread. This means about 1-3 microseconds of overhead for each light, which seems acceptable.
In scenes with many lights (above 10k), we have …
> Fixing testsuite issues using 21.02+ and supporting new and old light parameter naming conventions.

- render_delegate/render_delegate.cpp
- render_delegate/render_delegate.h
As it's being done in other parts of the code, we only call AiBegin/AiEnd if no Arnold session is active.
Note that this arnold API will be renamed as AiArnoldIsActive, in order to avoid confusions with universes that are something different. That's why the variable I'm adding is called isArnoldActive.
Fixes #884
> Only call AiBegin/AiEnd in the delegate if no arnold session is active

- render_delegate/render_param.cpp
- Avoid calling AiRenderBegin when render is already running.
Fixes #900
> Avoid calling AiRenderBegin when render is already running

- render_delegate/native_rprim.cpp
- Using GetVolumeShader if native rprim is volume.
Fixes #915
> Using GetVolumeShader if native rprim is volume

- translator/writer/writer.cpp
Just as we were doing for the default reflection shader, we're now ensuring we don't write out the default color manager node.
Fixes #924
> Don't write the default color manager node to usd 

- translator/writer/prim_writer.cpp
- translator/writer/writer.h
We add an API in `UsdArnoldWriter` to enable/disable the authoring of USD material bindings. When that option is enabled, we early out in `_WriteMaterialBinding`, thus we don't add `shader` and `disp_map` to the list of arnold attributes that were already exported. Then, in `_WriteArnoldParameters` , we don't see these attributes in the list so we author them as arnold custom attributes with the `primvars:arnold` namespace.
Note that, as the mayaUSD API evolves, we might not need this API anymore. This is why I'm not adding it to the scene format API.
Fixes #939
> Add writer API to skip material bindings #939

- render_delegate/render_delegate.cpp
This PR adds the render session pointer to all calls to `AiMsgSetConsoleFlags` / `AiMsgSetLogFileFlags`, so that they're applied to the delegate's render session
Fixes #953
> Add render session to AiMsg calls 

- procedural/main.cpp
We were calling `AiResolveFilePath` with `AtFileType::Custom` in the procedural. We just need to use `AtFileType::Procedural` instead.
Fixes #942
> Call AiResolveFilePath with procedural type

- schemas/SConscript
- schemas/createSchemaFile.py
- translator/reader/read_light.cpp
- translator/writer/write_light.cpp
In order to compile arnold-usd against USD 21.11, I've just had to do a few changes in the translator code regarding the removal of `UsdLuxLight` 
The code is still compatible with older versions of USD
Testsuite seems to be ok, so we don't need to update test scenes apparently
Fixes #957
> Support USD 21.11

- usd_imaging/material_param_utils.cpp
Adding ifdefs so that USD versions < 21.11 don't try to include files that didn't exist yet
Fixes #984
> Fix build issues in material_param_utils with USD 21.08

- render_delegate/node_graph.cpp
- testsuite/test_0048/data/scene.usda
When reading shader connections, we consider eventual array connections, using the format that we introduced in #375.
For example, if an array attribute `color` has a connection on its first element (index 0), we will expect in USD a connection on an attribute `color:i0`.  What the delegate needs to do in that case, is to replace that string with `color[0]` which is a format that arnold understands.
In the testsuite we have this use case in test_0048 (a ramp's array color connected to a shader), I verified that it worked well in Solaris. There was a mismatch with the test result though, that ended up being caused by the test scene itself : the output attribute wasn't defined in the scene. This is tolerated in the procedural but not in hydra. I've …
> Support connections to array elements in the delegate

- usd_imaging/node_graph_adapter.cpp
The ConnectableAPIBehaviour is only available from USD 21.11 see https://github.com/PixarAnimationStudios/USD/blob/v21.11/pxr/usd/usdShade/plugInfo.json
The early out relies on this from apiSchemaBase.h (UsdAPISchemaBase):
/// \note When the bool-conversion operator is invoked on an applied API 
/// schema, it evaluates to true only if the application of the API schema has
/// been recorded on the prim via a call to the auto-generated Apply() method.
To work around this we can skip the early and if the connectable behaviour is not available we will still return an empty HdMaterialNetworkMap since there will be no outputs.
Fixes #994
> Fix arnold node graph adapter for USD 21.08

- common/constant_strings.h
- translator/reader/read_geometry.cpp
- translator/reader/reader.h
Ensuring that point instancers can work with the "cache" procedural that accesses the usd stage through a cache id in the UsdStageCache. Whenever the point instancer needs to create a child procedural to instantiate a given hierarchy, it might need to create a cache proc and pass the cache id, instead of always creating a "usd" procedural and relying on the filename.
Fixes #996
> Support point instancer with a cache_id in the procedural

- render_delegate/render_delegate.cpp
This PR modifies the signature of AiMsg* calls to match with changes in the Arnold API while keeping the code backwards compatible for older versions. 
Fixes #1001
> Changing signature for AiMsg* calls (#1001)

- translator/reader/prim_reader.cpp
As we do in other arnold plugins, we need to check if a user data already exists before calling `AiNodeDeclare` in order to avoid eventual arnold warnings
Fixes #1014
> Remove harmless warnings when declaring a user data  #1014

- common/constant_strings.h
- procedural/main.cpp
- testsuite/test_0203/README
- testsuite/test_0203/data/scene.usda
- testsuite/test_0203/data/test.cpp
- translator/reader/reader.cpp
- translator/reader/reader.h
We add a possible paramMap "render_settings" when loading a usd file. If set, the reader will only pick a RenderSettings prim with this given name. If not set, only the first RenderSettings prim will be considered (currently all would end up being translated to the same arnold options node)
Fixes #1016
> Allow to specify a given RenderSettings prim when kicking a usd file

- render_delegate/node_graph.cpp
- render_delegate/render_delegate.cpp
Currently we have a warning in the render delegate code for connecting array elements
```
render_delegate/node_graph.cpp:830:54: warning: multi-character character constant [-Wmultichar]
size_t elemPos = outputAttr.find_last_of(':i');
^
render_delegate/node_graph.cpp:830:54: warning: implicit conversion from 'int' to 'std::basic_string<char>::value_type' (aka 'char') changes value from 14953 to 105 [-Wconstant-conversion]
size_t elemPos = outputAttr.find_last_of(':i');
```
This doesn't amount to a bug in the render delegate, but is in fact only searching for the last :, not the last :i since we pass a char not a string. If we has used a string it would pick the last of : OR i which is not what we want either.
We can fix by using rfind("i0") and updating the indices.
Note we only get …
> Fix for element connection in arnold node graph

- translator/reader/read_geometry.cpp
- translator/reader/reader.cpp
When we need to create a nested usd procedural for instancing purpose, we now also propagate the thread count to this procedural, so that we can properly debug scenes with a single thread
Fixes #1034
> Propagate thread count to nested procedurals for instancing 

- render_delegate/volume.cpp
Look for the _htoa_pygeo.so in either of the two possible python directories.
Fixes #955
> Check python 2.7 and 3.7 folders for HtoA libraries

- ndr/utils.cpp
- render_delegate/render_delegate.cpp
- translator/reader/registry.cpp
- translator/writer/registry.cpp
Adding version checks, so that we only call `AiArnoldIsActive` for Arnold 7.x versions
Fixes #1043
> Add version checks for older versions of Arnold

- translator/reader/prim_reader.cpp
- translator/reader/read_geometry.cpp
This PR verifies that we're not setting out-of-bounds vector elements in case primvars have invalid indices. 
I'm also verifying we're not trying to declare a user data for an attribute that already exists to prevent warnings that I've seen while debugging this.
I'm not managing to reproduce the crash with a simpler scene than the one provided by the customer, so I couldn't add a test  
Fixes #1045
> Fix crashes with invalid indexed primvars

- render_delegate/native_rprim.cpp
There is a warning of unused paramIt, I think the change in #743 made in #750 was intenend to have the new sceneDelegate->Get check outside the original parameter loop
Fixes #1047
> Fix for rprim sync in HdArnoldNativeRprim::Sync

- render_delegate/mesh.cpp
Just like it's done in the procedural, we're now setting the polymesh smoothing to be enabled by default in the delegate.
We were already doing similar in `HdArnoldMesh` for the `subdiv_iterations` that needed to be set to 0 by default.
Note that the `HdArnoldRprim`  constructor is different for usd versions older than 21.02. We had ifdefs for it, but they were containing the whole contructor function. I'm changing them to just change the function signature, which is enough and avoids code duplication on ech ifdef case.
Fixes #24
> Default mesh smoothing to true in the delegate

- render_delegate/basis_curves.cpp
- render_delegate/mesh.cpp
- render_delegate/utils.cpp
The render delegate already had some code to support velocity/accelerations when computing the positions (in `_ExtrapolatePositions` ), but a few things were missing :
- meshes and basis curves need to provide the primvars list to `HdArnoldSetPositionFromPrimvar` so that they can be used in `_ExtrapolatePositions`
- We were only considering velocities if positions were not animated. This isn't consistent with what the procedural is doing, and wuold still leads to issues. If the positions are animated and have varying topologies, then we wouldn't read the velocities, and this would still lead to errors. Instead, as soon as velocities/accelerations are provided, we should always consider them  instead of reading positions at different times.
- We were not necessarily considering the …
> Use velocity/acceleration primvars for mesh/curves in the render delegate

- common/constant_strings.h
- usd_imaging/node_graph_adapter.cpp
- usd_imaging/node_graph_adapter.h
Implement callbacks from the UsdImagingMaterialAdapter in materialAdapter.cpp to improve the IPR in the ArnoldNodeGraph adapter
Fixes #1057
> IPR improvements the arnold node graph adapter (#1057)

- common/constant_strings.h
- procedural/main.cpp
- translator/writer/writer.cpp
- translator/writer/writer.h
It's been requesting several times that we should set a defaultPrim when authoring usd files, as this can be required for file referencing. This PR sets one value for that. If an explicit value is provided we use it, otherwise if a scope is set we use it as the defaultPrim. If none of the params is set, then we use the top parent primitive, created by `UsdArnoldWriter::CreateHierarchy`
Fixes #1063
> Set the defaultPrim in the usd writer

- translator/writer/write_arnold_type.cpp
- translator/writer/writer.cpp
Instead of relying on the ArnoldOptions prim to store the list of frames, we now use the stage custom metadata, through a value called `timeCodeArray` (I used the same name as in one of the usd unit tests that stores such a list).
We no longer need to force the export of the options anymore, and we no longer need to force the export of the "frame" options attribute
Fixes #963
> Use custom metadata to store authored frames

- testsuite/test_0138/data/test.cpp
- testsuite/test_0208/README
- testsuite/test_0208/data/scene.ass
- testsuite/test_0208/data/test.cpp
- translator/writer/prim_writer.cpp
- translator/writer/writer.cpp
- translator/writer/writer.h
In this PR we're now authoring shaders under their respective material's scope. For that we've needed to do the following changes :
- we split the loop through arnold nodes to be written in 2. First for all nodes except shaders, and a second one with only shaders
- in `processMaterialBinding` we create a material based on the surface (and eventually displacement) shader. And we then set the material's path as the new writer scope while we trigger the export of surface/displacement shaders. This way the shaders will be written under the material's hierarchy, and it will propagate to the whole shading tree
- when we check if a node was already written (to avoid doing it multiple times), we ensure the scope is taken into account. Therefore the same …
> Write shading trees under their material's scope

- render_delegate/light.cpp
The light attribute tokens for temperature were changed in 21.02 and not in 21.05, we need to change the ifdef to build against 21.02
Fixes #1075
> Fix build issues with usd 21.02 

- schemas/createSchemaFile.py
We just need to add `point_light`  to the `nativeUsdList` so that generate the API schema for it (this ended up causing problems in mayaUSD as it relies on the API schemas)
Fixes #1081
> Add point_light to the list of schemas to be generated #1081

- translator/reader/read_camera.cpp
For some reason, in the camera reader we were using wrong functions by mistake to get the values for attributes "clippingRange" and "focusDistance". Instead of calling the usual "Get" functions, we were the "Create" functions that eventually create the attribute if it's not defined. 
Modifying the usd stage while traversing it in parallel was definitely not something to do, and this ended up causing crashes in specific scenarios
Fixes #1087
> Fix attribute calls in camera reader that were causing random crashes

- render_delegate/render_pass.cpp
- translator/reader/read_options.cpp
Fixes #1107
In the procedural we need to make sure we add the global aov_shaders after the primvar AOVs, currently they may overwrite them. Let's also change the ordering to match this in the render delegate.
> Add aov_shaders after primvar AOVs.

- translator/reader/utils.cpp
Recent commits are not building in USD 21.11. It's because one of the versions of `UsdGeomImageable::ComputeVisibility` has been removed. I'm computing it manually now, with the simple rule that visibility can either be `inherited` or `invisible`, and that a primitive is hidden if any of its ancestors is imageable and has visiblity set to `invisible`
> Fix build issue in procedural against USD 21.11

- usd_imaging/arnold_mesh_light_adapter.cpp
More fixes on the mesh light adapter, but for older versions of USD (20.11, 21.02). Some APIs were different back at the time.
> Fix builds for older versions of USD

- render_delegate/instancer.cpp
- render_delegate/instancer.h
- render_delegate/shape.cpp
- render_delegate/shape.h
- render_delegate/utils.cpp
- render_delegate/utils.h
In this PR we're now creating nested arnold instancers when we find nested instancers in the delegate.
Instead of storing a single instancer node for each shape, we're storing a list of instancers (from child to parent).
Since we no longer need to flatten the full list of instances for each shape, a lot of code could be removed about the "parent" and "child" instance counts. The code that handles the creation and translation of the arnold instancer was now moved from shape.cpp to instancer.cpp, so that it also can be done for nested instancers.
Since things are done quite differently now, we need to ensure it didn't cause any regression. There are several test scenes in our testsuite to verify this (183, 186, 188, 194, 196, etc...). So far all my …
> Optimize nested instances in the render delegate

- render_delegate/mesh.cpp
- render_delegate/utils.cpp
For recent versions of USD where we use indexed primvars differently, there was a typo in the code that reorders primvars indices for left-handed meshes.
When checking for out-of-bound indices in the primvar index arrays (in this case for `uvidxs` ), we were not comparing the indices correctly and skipping the values from the last polygon (there was a `>=` instead of a `>`).
Because of that, we were leaving the last few indices uninitialized, and that would randomly cause errors.
In the same vein, I'm also ensuring that we're not leaving uninitialized values in `nsides` when faces have no vertices, even though this is not what caused the original issue.
Fixes #1136
> Fix uninitialized UV coords with leftHanded meshes

- common/common_utils.h
- render_delegate/light.cpp
- render_delegate/node_graph.cpp
- render_delegate/node_graph.h
- render_delegate/node_graph_tracker.cpp
- render_delegate/node_graph_tracker.h
- render_delegate/render_delegate.cpp
- render_delegate/render_delegate.h
Fixes #1141
Looks for color, shader and light_filter# connections in the ArnoldNodeGraph referenced from the light primitive in the _primvars:arnold:shaders_ property.
> Light shaders

- render_delegate/camera.cpp
Fixes  #1151.
From USD 22.03, the DirtyProjMatrix and DirtyViewMatrix enums are removed from pxr/imaging/hd/camera.h and GetProjectionMatrix is replaced by ComputeProjectionMatrix.
> Build fix for USD 22.05

- render_delegate/render_delegate.cpp
- translator/reader/read_options.cpp
This PR renames the attributes used for aov_shaders, so that they conform to the format used for other attributes in arnold-usd.
Insted of being called `aov_shaders1`, these attributes will be called `aov_shaders:i1` .
The change is done both in the render delegate and in the procedural. But in the procedural, we're still supporting the previous format temporarily.
> Conform naming of aov_shaders attribute in the node graph

- render_delegate/light.cpp
Before checking the shaders connections to lights, we call `AiNodeResetParameter` on the light color to ensure IPR updates behave properly. But this is now overriding the code setting the light color attribute.
After looking more in depth at the code, there is already a `AiNodeReset(_light)` that resets the whole light before any attribute is set, so we don't actually need to reset any attribute in particular.
This PR removes the 3 attribute resets from this code, which fixes the issue with the lights colors
Fixes #1168
> Remove attributes reset in the lights delegate

- translator/reader/read_options.cpp
We were previously skipping all `RenderProduct` primitives with an empty `productName`. This was skipping all AOVs where the product name wasn't explicitely set.
Now, in this case we just use the product primitive name, and default to a .exr file.
Thus, by default, each AOV will render to a .exr file named as the render product.
In the case of merged .exrs, when all AOVs (RenderVars) are part of the same render product, then rendering with `kick -o output.exr` will therefore override the filename for all AOVs.
Fixes #1170
> Support render products with no productName

- translator/writer/prim_writer.cpp
When we convert arnold per-channel connections to USD, we insert an adapter shader  `float_to_rgba`. This PR ensures that we create its output attribute, and that the shading connection is done with this attribute. This doesn't affect the usage of the procedural, as the output attribute name doesn't have any impact in that case, and it's why several tests were already exercising this (e.g. test_0059). But in Hydra, this was causing wrong results
Fixes #1175
> Fix authoring per-channel connections 

- ndr/parser.cpp
Rolling back the changes in #974 that changed `SdrShaderNode` and `SdrShaderProperty` by `NdrNode` / `NdrProperty`.
This isn't causing regressions in my tests, but might need more verifications
Fixes #1131
> Revert to SdrShaderNodes for discovery plugin

- translator/reader/read_options.cpp
The changes in #1162 weren't ported properly to the procedural, so we were not reading the aov_shaders properly
> Fix aov shaders through nodegraphs in the procedural

- common/constant_strings.h
- procedural/main.cpp
- translator/reader/read_geometry.cpp
- translator/reader/reader.cpp
- translator/reader/reader.h
When we need to create nested usd procedurals for instances, we were relying on a usd filename, which caused lots of randomness issues (prototype names aren't consistent). 
We also had to do complex setups for variants overrides, transforms on the instanceable prim, etc... 
In this PR, we switch to using a UsdStageCache and a cacheId in the nested procedurals. When the usd reader needs to create a nested usd proc, it now stores its stage in the stage cache, and passes it to the child procs. This way, the child procs will share the same stage, and there won't be any randomness.
We use a reference counting system, so that once all the procedurals finished reading the data, we release the memory from the stage.
We have a special case when we resave …
> Use cache_id for instance nested usd procedurals

- common/constant_strings.h
- render_delegate/basis_curves.cpp
- translator/reader/read_geometry.cpp
- translator/writer/write_geometry.cpp
Fixes #800.
Pass the wrap_mode through to the arnold shape from the usd primitive and hydra, conversely set wrap attribute from arnold in the writer.
> Curve pinning for the render delegate, reader and writer

- render_delegate/render_pass.cpp
- translator/reader/read_options.cpp
For cryptomatte, we need to customize the AOVs data type, so that it's considered differently by Hydra and by Arnold.
This way, the AOVs like crypto_material00, etc... would be float for Arnold outputs, but RGBA for Hydra.
Fixes #1164
> Add arnold:format attribute in RenderVars

- render_delegate/node_graph.cpp
- translator/reader/read_shader.cpp
This PR reads arnold-specific shaders coming from Materialx, and translates them to regular arnold shaders.
If materialx could find these shaders, they will be translated to USD with an info id starting with `ARNOLD_ND_`
I also did a bit of cleanup by using `strncmp` as in other parts of the code, instead of manually checking the first characters
> Support arnold-specific shaders in materialx

- render_delegate/node_graph.cpp
In the render delegate, we were not reading correctly standard_surface shaders coming from a materialx document, due an error in some string comparisons
> Fix issue with mtlx standard surface in the render delegate #1181

- translator/reader/read_shader.cpp
In the procedural, the attribute usdSpecularWorkflow was not interpreted correctly. This PR fixes it
Fixes #1183
> Fix usdPreviewSurface attribute useSpecularWorkflow in the procedural

- render_delegate/node_graph.cpp
As described in #1217, the ifdefs weren't correctly placed. Fixing it so that we don't try to call APIs that don't exist for a given version of arnold
Fixes #1217
> Fix build issue with older versions of Arnold 

- CMakeLists.txt
- SConstruct
- cmake/utils/options.cmake
- render_delegate/CMakeLists.txt
- render_delegate/node_graph.cpp
- translator/reader/read_shader.cpp
This PR temporarily comments out the code needed to read materialx shaders, both in the procedural and in the delegate, as the USD static libs currently shipped with Arnold don't include the materialx plugin. An environment variable can restore it.
In the Cmake files, I'm removing the previous materialx build variables that are no longer relevant.
I'm commenting out the tests based on the arnold version since they're not needed with the new build variable. But I'm keeping them as comments so that we don't forget to restore them when the build variable is no longer needed
> Disable MaterialX shaders unless variable is defined

- procedural/macos_export_list
- procedural/macos_export_list_no_scene
- on macOS it allows to export only the symbols belonging to USD. Most of them are weak external symbols.
Fixes #1226
> re-export core usd libraries symbols on macOS

- procedural/SConscript
- procedural/macos_export_list_shared
The fix done in #1227 wasn't actually enough, and we were still getting crashes with some scenes.
For now, when we build against shared usd libs on Mac, we should *not* try to hide the usd symbols.
Fixes #1226
> Don't hide any usd symbols on Mac for shared usd libs

- ndr/parser.cpp
- ndr/utils.cpp
When we parse the arnold node entries to create sdr Shader properties, we also create an output attribute called `outputs:out` with a type based on the arnold output type
Fixes #1211
> Register arnold outputs as Sdr output properties

- render_delegate/config.cpp
In the render delegate config.cpp, where environment variables can be set for some render settings, specific defaults are set for some attributes. For the samples attributes, the values don't match what we usually set as defaults.  These default values happen to be used when rendering in husk (not in interactive Solaris rendering, not when exporting to usd to kick the files).
So for example, if "Diffuse Samples" isn't explicitely set, in interactive rendering or kick, it will be left to the default value of 2. But in husk it will default to 1, as this is the value set in config.
Likewise, AA_samples is 10 by default in husk rendering, which seems too much.
This PR sets these sampling values in a way that matches what's done in other arnold plugins. AA_samples defaults to 3, and the other …
> Fix default render settings values set in the render delegate config

- translator/reader/utils.h
- Check if the texture path is empty before trying to resolve it
Fixes #1246
> Check if the texture path is empty before trying to resolve it

- render_delegate/render_delegate.cpp
Declaring abort_on_error, so that it now shows up in mayaUSD render options for arnold.
Fixes #1259
> Declare abort on error as a hydra render settings

- ndr/parser.cpp
The changes done in #1258 were manually stripping the output.
As suggested in this PR after it was merged, we should instead use `UsdProperty::GetBaseName()` for output attributes
> Use GetBaseName instead of manually extracting the namespace

- common/constant_strings.h
- render_delegate/basis_curves.cpp
This PR ports the same changes done in #1216 to the render delegate.
For pinned curves, primvars with vertex interpolation should *not* me remapped as we usually do.
I verified in the test_0239 scene, it now renders as in the procedural
Fixes #1240
> Don't remap vertex primvars for pinned curves #1240

- render_delegate/render_delegate.cpp
- We don't return a dummy GeometryLight without path to the geo to avoid the warning. This is a fallback geo and we are not using it, so we shouldn't need to create one in the first place.
Fixes #1275
More infos on fallback prims in the usd forum : https://groups.google.com/g/usd-interest/c/O4llDTmnc7k/m/Hd9fbjFwDgAJ
> avoid creating a fallback dummy geometry light by returning nullptr

- common/constant_strings.h
- render_delegate/render_param.cpp
- render_delegate/render_param.h
When the env variable `HDARNOLD_DEBUG_SCENE` is defined, the render delegate will save it out before each render iteration. 
This allows to debug how the delegate translates hydra data into arnold.
Fixes #1266
> Add env variable in the delegate to save the arnold scene before rendering it

- translator/reader/read_geometry.cpp
In the volume reader, we were testing if the field density primitive had the proper type (UsdVolOpenVDBAsset) but we were simply not testing if the primitive existed.  So if the path was invalid we were crashing. 
Fixes #1281
> Avoid crashes when invalid primitive path is set for a volume's field

- SConstruct
- Setting INSTALL_USD_PLUGIN_RESOURCES will trigger the copy of the plugin/usd folder onto the install destination 
Fixes #1302
> adds plugin resources when INSTALL_USD_PLUGIN_RESOURCES is set

- SConstruct
- tools/utils/regression_test.py
- This adds ENABLE_HYDRA_TEST to abuild, to enable the use of the hydra_test renderer. The value is False per default
- Fix a bug where the tests using ass scripts were failing.
Fixes #1324
> add ENABLE_HYDRA_TEST variable and fix missing script issue

- render_delegate/CMakeLists.txt
- render_delegate/basis_curves.cpp
- render_delegate/mesh.cpp
- render_delegate/utils.cpp
- render_delegate/utils.h
- tools/utils/dependencies.py
In this PR we had support for motion blur in skinned geometries. For the "points" primvar, we need to call `HdExtComputationUtils::SampleComputedPrimvarValues` instead of `HdExtComputationUtils::GetComputedPrimvarValues` which will return different values for each time sample. For now we're only doing this for the points primvar, since some primvars shouldn't be animated in Arnold.
Fixes #738
> Support motion blur on skinned instances in Hydra

- testsuite/SConscript
The previous PR wasn't setting PRX_PLUGIN_PATH_NAME  to the right folder, for the testsuite
> Fix PRX_PLUGIN_PATH_NAME path for testsuite

- render_delegate/utils.cpp
HdExtComputationUtils::SampledValueStore was defined only from USD 21.05 and up. This PR ensures we can still compile (and roll back to the previous behaviour) in older versions
> Fix build issues in older versions of USD

- translator/reader/read_geometry.cpp
In this PR, when we evaluate user primvars for an instancer, we evaluate them at a single time and disable animation for now.
Animated user datas aren't supported in instancers at the moment, so this is a workaround until it's properly addressed in arnold core.
Fixes #1298
> Disable animation for instancer user primvars

- common/constant_strings.h
- render_delegate/config.cpp
- render_delegate/config.h
- render_delegate/render_delegate.cpp
This PR declares a new env variable `HDARNOLD_auto_generate_tx` that can be used to override the default value of autoTX
Fixes #1353
> Add env variable for autoTX 

- CMakeLists.txt
- SConstruct
Simply adding the `/DEBUG` compile flag on windows, both in Scons and Cmake
Fixes #1360
> Build symbols on windows

- ndr/parser.cpp
- ndr/utils.cpp
We were computing the node entry metadatas in `_ReadArnoldShaderDef` (utils.cpp), but we were just using "ui.groups` to create the attributes in a given order and grouping. 
In this PR we also provide the Role and Help metadatas at the shader node level. 
Fixes #1368
> Provide Role and Help metadatas at the shader level 

- translator/reader/reader.cpp
In this PR, when we find a primitive with `purpose` set to an empty string, we consider this to be equivalent to the default value `default` .
Fixes #1372
> Read primitives with empty purpose

- SConstruct
When building arnold-usd we ensure that ADP is disabled. 
This can have an effect when we build schemas, or SDR registry, which require to invoke AiBegin / AiEnd to get the list of arnold node entries
> Ensure ADP is disabled during arnold-usd builds

- render_delegate/render_delegate.cpp
This PR ensures that batch hydra renders disable CER, so that we don't get windows showing up during batch renders
> Ensure CER is disabled during batch hydra renders

- SConstruct
Using `EnumVariable` forces to update the allowed values every time a new one we want to support. This simply turns the `MSVC_VERSION` parameter into a string.
> Allow to select any MSVC_VERSION in SCons build system

- translator/reader/registry.cpp
- translator/writer/registry.cpp
- translator/writer/write_geometry.cpp
We were testing ARNOLD_VERSION_NUMBER to use `AiArnoldIsActive` instead of `AiUniverseIsActive` , but without including `../arnold_usd.h` that properly defines this variable
Fixes #1387
> Ensure arnold_usd.h is included when needed

- ndr/parser.cpp
- ndr/utils.cpp
Instead of only adding 2 hardcoded metadatas to the map passed to the Sdr Registry, we loop over all the metadatas found in this node entry
Fixes #1390
> Declare all node metadatas in Sdr registry

- translator/writer/writer.cpp
- The writer will now write the arnold fps to the layer metadata Frame per second and TimeCode per second.
Fixes #1395
> convert arnold fps to usd frame+timecode per second

- common/constant_strings.h
- ndr/utils.cpp
- translator/writer/prim_writer.cpp
In this PR, we're authoring "filename" arnold attributes as SdfAssetPath in USD. This no longer requires changes in the usd reader, since we now handle the conversion at read-time, and support not resolving the usd paths.
In order to find out if an attribute is a filename, we look for its metadata `file` and check if it's set to `path`
The change also needs to be done in the Sdr registry, since we should now declare these attributes as being SdfAssetPath
Fixes #1163
> Declare filename attributes as asset Paths

- ndr/parser.cpp
- ndr/utils.cpp
The fix done in #1418 wasn't doing the right thing. For "asset" attributes, we need to declare them as string attributes, with a metadata IsAssetIdentifier set to true.
This is actually simpler and cleaner than the first PR
Fixes #1163
> Restore asset attributes as string in the registry, with the proper metadata

- render_delegate/render_delegate.cpp
- render_delegate/render_delegate.h
- render_delegate/render_pass.cpp
- render_delegate/render_pass.h
Support for Render delegate products is now generalized, and no longer hardcoded for `deep` . If one sets the name of an arnold driver in the product type field, then the arnold render delegate will create such a driver instead of relying on Hydra drivers.
For example, if we set `driver_exr` in the render product in Solaris, and then render with husk, the render rely on a driver_exr and therefore render as if it was using kick-usd. 
Still missing : pass on the arnold render product parameters (i.e. the list of driver attributes) to the driver. At the moment they're ignored and only the deep exr params are supported.
Fixes #1422
> Generalize support for render delegate products

- testsuite/test_0173/data/test.usda
Updated test_0173 as using Arnold Spheres will account for UVs for this test. Related to changed introduced in #1318.
> Updated test_0173 to use Arnold Spheres

- testsuite/test_1457/README
- testsuite/test_1457/data/scene.ass
- testsuite/test_1457/data/test.cpp
- translator/writer/prim_writer.cpp
- translator/writer/writer.cpp
- translator/writer/writer.h
When we write a shader primitive, we force it to be under the hierarchy of the material it's assigned to.
But because of that, when the whole USD scene is exported under a given scope, then we will find the scope twice under the shader.
This PR strips this scope before writing the usd prim, so that we get the expected scene hierarchy
Fixes #1457
> Ensure shader scope doesn't appear twice in the hierarchy

- SConstruct
Add a build variable TESTSUITE_OUTPUT to specify where the testsuite results should be dumped
Fixes #1480
> Allow to specify testsuite output folder #1480

- schemas/createSchemaFile.py
During the schemas generation, we need to ignore new material nodes since we're already creating a ArnoldMaterial schema
> Fix schemas creation caused by new material nodes

- CHANGELOG.md
- render_delegate/basis_curves.cpp
- render_delegate/utils.cpp
This PR ensures that we don't call AiArrayMap / AiArrayUnmap with empty arrays, which can happen sometimes when primvars are empty arrays.
Fixes #1502
> Ensure we don't map/unmap empty arrays

- CHANGELOG.md
- SConstruct
In this PR we convert the python / boost / tbb paths to be absolute paths in the Sconstruct
Fixes #1508
> Support relative paths for python / boost / tbb

- render_delegate/render_delegate.cpp
- render_delegate/render_param.cpp
- render_delegate/render_param.h
- Replace std::atomic + chronos::time_point usage with a std::mutex, as time_point isn't guaranteed to be trivially copyable
- Fix compile errors on Linux/Mac
> Fix render delegate compile errors on Linux

- CHANGELOG.md
- CMakeLists.txt
- SConstruct
- cmake/utils/options.cmake
- render_delegate/node_graph.cpp
- translator/reader/read_shader.cpp
We no longer need the ENABLE_MATERIALX build variable, since we can just check for arnold versions being >= 7.1.4.0.
Fixes #1512
> Remove deprecated ENABLE_MATERIALX build variable

- CHANGELOG.md
- schemas/createSchemaFile.py
The filename attributes have been modified to be set as assets instead of strings. But this change had to be ported to the schemas
Fixes #1532
> Declare filename attributes as assets in the schemas

- render_delegate/render_param.cpp
- render_delegate/render_param.h
- Now caching the Arnold render status in a global string (protected by a mutex), instead of in a variable owned by render_param.
Fixes [#1572](https://github.com/Autodesk/arnold-usd/issues/1572)
> USD 1572 | Fix crash when restarting an interactive render

- SConstruct
The changes done for the libs refactoring broke the render delegate build. 
This PR fixes a few typos, and it's allowing the builds to work again
> Fix render delegate build issues

- testsuite/test_0003/data/sphere.usd
- testsuite/test_0004/data/sphere.usd
- testsuite/test_0005/data/sphere.usd
- testsuite/test_0006/data/sphere.usd
- testsuite/test_0007/data/sphere.usd
- testsuite/test_0008/data/sphere.usd
- testsuite/test_0009/data/sphere.usd
- testsuite/test_0009/data/test.ass
- testsuite/test_0022/data/scene.usd
The procedural, even when built against the latest USD, still supports the "old" light format, where the "inputs:" namespace didn't exist. This want meant to be able to kick usd files exported from older versions of Solaris. But this is less important on the render delegate side, it's more tricky to do, and we will soon be able to drop support for the old format. 
So we won't be doing any fix in the code for now, we'll just fix the test scenes, so that they are based on the new format
Fixes #1543
> Update oldest test scenes for light attributes

- CHANGELOG.md
- libs/render_delegate/render_pass.cpp
- Read the RenderVar arnold:format attribute and use it as the aov format if it is declared 
- Read the RenderVar arnold:filter and use the defined filter as the aov filter.
Fixes #1595
> Support Arnold RenderVars filters and format

- SConstruct
- Added basic coloured compiler commands for clearer multi arch building
- SHOW_CMDS=False will enable the shortened commands
- COLOR_CMDS can be used to set if they're colourful or not
Windows build:
This is handy when dealing with multiple archs:
Fixes #
I've used ansi codes explicitly to avoid any additional dependencies (i.e. colorama), but let me know if this is a bad idea
> Add architecture to the compiler commands

- SConstruct
- Use the built procedural folder as the source for the installation of resource instead of the usd directory
Fixes #1601
> Fix procedural resources source folder

- libs/common/parameters_utils.cpp
- libs/common/parameters_utils.h
- libs/translator/reader/read_arnold_type.cpp
- libs/translator/reader/read_geometry.cpp
- libs/translator/writer/write_arnold_type.cpp
- testsuite/test_0015/data/scene.usda
- testsuite/test_0034/data/scene.usda
- testsuite/test_0043/data/proc.usd
- testsuite/test_0050/data/test.usda
- testsuite/test_0088/data/test.ass
- testsuite/test_0101/data/test.ass
- testsuite/test_0107/data/test.ass
- testsuite/test_0116/data/test.ass
- testsuite/test_0132/data/test.usda
- testsuite/test_0139/data/test.usda
- testsuite/test_0140/data/test.usda
- testsuite/test_0145/data/test.usda
- testsuite/test_0151/data/test.usda
- testsuite/test_0161/data/nested_proc.usda
- testsuite/test_0162/data/nested_proc.usda
- testsuite/test_0170/data/test.usda
- testsuite/test_0173/data/test.usda
- testsuite/test_0186/data/test.usda
- testsuite/test_0194/data/test.usda
- testsuite/test_0196/data/test.usda
- testsuite/test_0213/data/test.usda
- testsuite/test_0214/data/test.usda
- testsuite/test_0225/data/test.usda
- testsuite/test_0242/data/test.usda
- testsuite/test_1237/data/test.usda
This PR removes the deprecated attribute format for typed schemas. They require an arnold: namespace, and we're no longer supporting formats without it.
Several test scenes were outdated and are fixed here. 
Also, the writer was still authoring attributes without this namespace for ArnoldGinstance primitives
> Deprecate old typed schemas format

- testsuite/test_0002/README
- testsuite/test_0010/README
- testsuite/test_0012/README
- testsuite/test_0014/README
- testsuite/test_0021/README
- testsuite/test_0163/README
- testsuite/test_0183/README
- testsuite/test_0195/README
- testsuite/test_0202/README
- testsuite/test_0206/README
- testsuite/test_0216/README
- testsuite/test_0228/README
- testsuite/test_1309/README
- testsuite/test_1313/README
This PR adds a relatively small hardfail threshold for some tests that show almost the same result between hydra and usd
> Add threshold to some tests for hydra

- CHANGELOG.md
- libs/render_delegate/reader.cpp
- libs/render_delegate/reader.h
- libs/render_delegate/render_delegate.cpp
- libs/render_delegate/render_delegate.h
When the render delegate is used through a procedural, we need to ensure some nodes are filtered out (options, etc..).
This PR adds the node mask that is already used in the USD reader, and uses it to eventually skip certain nodes to be created by the render delegate. This fixes a few more tests in "hydra" mode
Fixes #1644
> Support nodes mask in the hydra procedural

- libs/common/shape_utils.cpp
The changes introduced in #1636  are not building with older versions of USD. A simple include is missing
> Fix build issue with older usd cuts ARNOLD-14004

- tools/usdgenschema/SConscript
Fixing a build issue with an undefined variable in a specific use case on linux
> Fix usdgenschema on linux

- libs/render_delegate/reader.cpp
- testsuite/test_0031/README
- testsuite/test_0031/data/test.ass
- testsuite/test_0032/data/test.ass
This PR adds support for overrides when a usd file is read, going through the render delegate. This fixes test_0017 in hydra mode. Tests 31 and 32 needed to set the cube smoothing attribute as we did in other tests.
Right after these last PRs are merged, I'm planning to factorize the code used in both usd and hydra readers, as there's more and more stuff in common. 
Fixes #1585
> Support overrides in hydra procedural

- CHANGELOG.md
- libs/render_delegate/reader.cpp
- testsuite/test_0020/README
This PR checks the root path specified by the procedural, in hydra mode, and only reads the usd stage from that primitive.
It fixes test_0020, although a tiny threshold needs to be added due to the cone tessellation
Fixes #1587 
> Support object path in hydra procedural

- plugins/procedural/main.cpp
So far we were using the hydra procedural as soon as the variable PROCEDURAL_USE_HYDRA is defined. But it can be useful to switch this variable back and forth so in this PR I'm checking its value. If it's set to "0" we use the regular usd procedural, but otherwise we create the hydra reader
> Check the value of PROCEDURAL_USE_HYDRA instead of if it's defined

- CHANGELOG.md
- libs/common/CMakeLists.txt
- libs/common/SConscript
- libs/common/procedural_reader.cpp
- libs/common/procedural_reader.h
- libs/render_delegate/reader.cpp
- libs/render_delegate/reader.h
- libs/translator/reader/reader.cpp
- libs/translator/reader/reader.h
This PR factorizes some of the code that was duplicated between the hydra and the usd reader, and moves it to the ProceduralReader class. Now the class that needs to be overridden is ReadStage that will work for usd filenames or a stage cache ID.
Fixes #1664
> Refactoring to add support for cacheID in the hydra delegate

- testsuite/SConscript
Some tests are running several processes, like those that resave a scene and then kick the resaved scene. In this case, the log file is being overwritten over and over. This change ensures the log is appended so that we can get the full info.
> Ensure testsuite logs are appended for resaved tests

- CHANGELOG.md
- libs/render_delegate/mesh.cpp
- reassign the _geometryLight variable which was remove during the refactoring of the render delegate.
Fixes #1693
> Fix geometry light not working in 7.2.3+

- SConstruct
If we compile the procedural with ENABLE_HYDRA_IN_USD_PROCEDURAL , and some other build parameters are disabled, the build currently fails.
This hydra procedural requires schemas, ndr and usd_imaging plugins, so their build flags need to be enabled.
This PR ensures the build flags are properly set by forcing BUILD_SCHEMAS, BUILD_USD_IMAGING_PLUGIN and BUILD_NDR_PLUGIN  when the hydra procedural is compiled
> Ensure plugins build flags are properly set for the hydra procedural

- tools/usdgenschema/SConscript
This PR will force usdGenSchema to be built for the host architecture, since it's a tool run during the build process.
> Build usdGenSchema for the host architecture

- libs/render_delegate/camera.cpp
- libs/render_delegate/render_pass.cpp
Older versions of USD didn't support orthographic projections in HdCamera. 
This PR adds some ifdefs to ensure the code compiles properly with e.g. USD 20.11
I'm also simplifying a bit a previous set of ifdefs that could be factorized as a single one.
> Fix render delegate build with older versions of USD

- schemas/SConscript
When calling `schemas/createSchemaFile.py` we were appending the Arnold Python API path to the environment variable PYTHONPATH. That could clash with other python modules which might have also `arnold` as its main namespace.
We can fix this by simply prepending the path instead, so we ensure that it's the `arnold` module that we are looking for.
> Fix PYTHONPATH construction for properly using the Arnold Python API

- SConstruct
As it's done in other arnold projects, we're making it so that by default with Scons we build with all the available cores.
> Build with the maximum amount of threads by default in Scons

- SConstruct
- libs/render_delegate/utils.cpp
- libs/translator/reader/utils.h
- tools/usdgenschema/main.cpp
Building arnold-usd on windows is currently triggering a lot of compilation / linking warnings.
This PR fixes them by : 
- ignoring 2 linking issues coming from how we link against USD "4099" and "4217"
- adding a variable that ignores TBB deprecation messages (also coming from USD)
- Properly cast variables in two pieces of code. When going through vectors, the implicit type conversion was causing warnings
- A recent change wasn't always returning a value in a function
All these changes give us a clean build log, without warnings
> Fix compilation warnings on windows

- SConstruct
With this change, if the testsuite is executed with BUILD_PROCEDURAL=False, then we won't force this variable to be enabled, and we'll explicitely look for the usd procedural included in the arnold SDK
> Use the Arnold SDK procedural in testsuite if BUILD_PROCEDURAL is off

- CHANGELOG.md
- libs/render_delegate/render_pass.cpp
- Revert change made in revert change made in https://github.com/Autodesk/arnold-usd/pull/1697 as they were working with cryptomatte in houdini but were not in nuke.
Fixes #1728
> Restore cryptomatte filters assignment

- CHANGELOG.md
- libs/render_delegate/render_pass.cpp
- Avoid testing the lpe for the beauty in the render delegate to be consistent with the procedural behaviour
Fixes #1732
> Force the color aov to be interpreted as the Arnold beauty pass, regardless of the LPE

- CHANGELOG.md
- libs/render_delegate/render_delegate.cpp
When we parse the command line arguments in the render delegate (which at the moment is specific to husk), we now look for an argument -j or --threads that is used to specify the amount of threads.
Unortunately this is hard to test, since the options attribute "threads" is an exception and is never saved to ass files
Fixes #1077
> Add support for -j argument in husk #1077

- CHANGELOG.md
- libs/render_delegate/render_delegate.cpp
- libs/render_delegate/render_delegate.h
- libs/render_delegate/render_pass.cpp
This PR adds support for pixel aspect ratio as a hydra render setting. We need to eventually combine it with some existing code that uses pixel aspect ratio for anamorphic windowNDC settings.
We already have tests with pixel aspect ratio settings, but the testsuite cannot exercise this code path with hydra render settings.
Fixes #658
> Add support for pixel aspect ratio in the render delegate

- SConstruct
- Update SConstruct to pass the C++ standard version to msvc
> pass the C++ standard argument to msvc

- CHANGELOG.md
- libs/translator/reader/utils.h
Crashes where reported in ARNOLD-14028, which happen when we try to get the value of an attribute which type isn't supported.
At the moment, after testing specific attribute types in VtValueGet* functions, we do a blind value.Get with the type that we want to convert it to.
But apparently, this can sometimes crash in USD when the types don't match. Now, we're instead returning a 0-value when the value doesn't hold any of the types that are supported
> Return a zero value when an attribute type is not recognized

- SConstruct
On windows, if CXX_STANDARD is not set, it will default to 11.
The recently introduced code that adds the argument /std:c++ is now dumping a lot of warnings in this case, since this argument
doesn't work with /std:c++11
> Fix windows warning with default CXX_STANDARD

- libs/common/parameters_utils.h
- libs/render_delegate/utils.cpp
This PR removes the delegate's specific conversion functions, and uses instead the VtValueGet* functions.
It's a first step to factorize even more both code paths (e.g. the whole HdArnoldSetParameter function)
Fixes #1767
> Use VtValueGet functions from the render delegate

- CHANGELOG.md
- SConstruct
- Replace USD_BIN PathVariable by a StringVariable which won't check if the path exists.
Fixes #1793
> Allow scons compilation without USD_BIN

- SConstruct
- tools/usdgenschema/SConscript
- revert a patch that allowed to run usdgenschema on a non M1 machine using arnold build system
- added a variable to enable the patch as otherwise it won't work on m1 machines
> Quick fix to compile on the ADSK CI with arnold build

- CHANGELOG.md
- libs/translator/writer/writer.h
- plugins/procedural/main.cpp
The WriteUsdStageCache API isn't exercised yet, it's meant to be used by MtoA and MAXtoA to avoid linking against USD.
It just had a "frame" argument hardcoded, but we actually want to extend it to have roughly the same set of optional parameters as `scene_write` . For that we use now a `AtParamValueMap` so that any argument can be added without changing the API signature. Since this isn't exercised yet, it might not be useful to add a note in the changelog
> Extend the WriteUsdStageCache API

- CHANGELOG.md
- libs/render_delegate/volume.cpp
- Look into subfolders named against more recent version of python.
- This is not a future proof solution and we should find a better alternative with HTOA.
Fixes #1808
> Fix the error "Cannot load _htoa_pygeo library required for volume rendering in Solaris" in houdini 19.5+

- libs/render_delegate/instancer.cpp
A previous commit broke compilation with older versions of USD, where some tokens are not defined. 
Here I'm unifying the declared tokens independantly of the usd version
> Fix compilation with older version of USD

- CHANGELOG.md
- libs/render_delegate/node_graph.cpp
- libs/render_delegate/render_delegate.cpp
- libs/render_delegate/render_delegate.h
- The functions AiMaterialXGetNodeEntryFromDefinition and AiMaterialXGetOslShaderCode are costly and we called them for every shader prim. The easiest solution is to cache the returned node entry associated to a particular shader type. We do the same for the osl code.
Fixes #1812
> Improve material network creation times by caching the nodes returned by Arnold

- libs/translator/reader/read_geometry.cpp
We need to put some more ifdefs on the lights translator code, to support older versions of USD
> Fix compilation against older USD cuts

- testsuite/SConscript
- tools/utils/regression_test.py
This PR adds the skip_license_check argument to the testsuite kick command lines, as well as an environment variable to avoid aborting when no license is found
> Skip license check during testsuite

- libs/common/api_adapter.h
- libs/common/materials_utils.cpp
- Since https://github.com/Autodesk/arnold-usd/pull/1819 some hydra tests are failing (test_1538, test_1333, test_1181), this PR fixes those issues by correctly creating the key for the materialx node entry cache.
> Fix failing Materialx tests on hydra testsuite 

- CHANGELOG.md
- libs/render_delegate/volume.cpp
- update changelog
- add missing commit #1811
> Merge fix 7.2.5 in master

- CHANGELOG.md
- libs/translator/reader/reader.cpp
- libs/translator/reader/reader.h
- Make the UsdArnoldReaderRegistry non static to fix the crash happening in maya.
- The motion blur still need to be fixed in another pull request
Partially Fixes #1781
> Fix crash happening in maya aiStandin when scrolling the timeline

- SConstruct
- add a compilation flag to ignore the warning "warning C4003: not enough arguments for function-like macro invocation 'BOOST_PP_SEQ_DETAIL_EMPTY_SIZE'" with msvc and usd 23.11
> Fix compilation warning with msvc and usd 23.11

- libs/common/api_adapter.h
This PR fixes a compilation warning happening in MAXtoA. Since the class `ArnoldApiAdapter` has virtual methods, we need to add a virtual destructor.
> Fix compilation warning in MAXtoA

- SConstruct
- plugins/procedural/SConscript
We shouldn't be forcing the build of ndr / schemas / usdImaging when the hydra procedural build is enabled. These libs are loaded by USD, and can be compiled separately (as it's done in MtoA)
Fixes #1839
> Support hydra procedural with a shared USD

- libs/render_delegate/volume.cpp
- Changed HtoAConvertPrimVdbToArnold symbol lookup from pythonX.Xlibs/_htoa_pygeo lookup to scripts/bin/<htoa_geo dso> (the name differs per platform)
- This gives us the slight benefit of no longer needing to maintain the python versions table.
- I'll add a test to validate this in HtoA, so if it breaks again in the future we'll know.
Happy Windows teapot VDB:
Fixes [arnold-usd#1848](https://github.com/Autodesk/arnold-usd/issues/1848)
> Change HtoAConvertPrimVdbToArnold symbol lookup to htoaGeo lib

- CHANGELOG.md
- libs/render_delegate/camera.cpp
- We are testing if the camera is a perspective or ortho camera in the render delegate camera sync. Unfortunately the test was incorrect as the type returned by the function AiNodeEntryGetTypeName is the generic type "camera" and not the specific type of the camera persp_camera or ortho_camera. A new arnold camera was created everytime there was a change in parameter, thus forcing an update of the scene.
Fixes #1854
> Fix slowness in the render delegate due to scene update when the camera moves

- SConstruct
This PR enables a built-in option in SCons ([`MSVC_USE_SCRIPT`](https://scons.org/doc/production/HTML/scons-man.html#cv-MSVC_USE_SCRIPT)) in order to override the default detection from [`MSVC_VERSION`](https://scons.org/doc/production/HTML/scons-man.html#cv-MSVC_VERSION)
> Enable MSVC_USE_SCRIPT Scons option to override default MSVC_VERSION detection

- docs/documenting.md
- tools/scons/scons-README
There are multiple broken links in the documentation of this project. Here is what I have fixed:
http://www.scons.org/download.html --> https://scons.org/pages/download.html
http://www.scons.org/doc.html --> https://scons.org/documentation.html
http://two.pairlist.net/mailman/listinfo/scons-users --> https://pairlist2.pair.net/mailman/listinfo/scons-users
http://www.doxygen.org/manual.html --> https://www.doxygen.nl/manual/index.html
I found these links using a tool I created called [link-inspector](https://github.com/justindhillon/link-inspector). If you find this PR useful, give the repo a ⭐
I have also applied to the [Intern, Front End Developer](https://autodesk.wd1.myworkdayjobs.com/en-US/Ext/job/Intern--Front-End-Developer_24WD74757) position at your company. If you could put a word …
> Fix Broken Links

- libs/common/common_utils.h
- libs/common/parameters_utils.cpp
- plugins/ndr/utils.cpp
In order to solve all the occurrences of AI_NODE_DRIVER referring to imagers, we're defining AI_NODE_IMAGER for older versions of Arnold
> Fixes for imager node type

- libs/translator/reader/read_geometry.cpp
- libs/translator/reader/reader.cpp
A complementary change to what was done in #1847  for #168 . I'm removing the previous AiNodeReset that shouldn't be needed  during interactive updates (and that can cause slowdowns). Also, I'm moving all ReadMatrix calls in read_geometry to happen before other parameters are set (nsides, vlist, etc...). This doesn't change the data that is created, but the order of operations does workaround an existing issue in arnold (ARNOLD-14829)
Fixes #168
> Move the ReadMatrix code to workaround existing arnold issues

- CHANGELOG.md
- libs/render_delegate/light.cpp
When a Dome primitive has a texture filename, we create an image node in the arnold scene.
In Hydra it creates an image node with an empty name though, which can cause problems, e.g. when saving out .ass files. This PR follows the same naming as in the translator code.
> Set a proper name to skydome image node in Hydra

- tools/utils/regression_test.py
Tiny PR, that is just for internal testsuite execution. Some tests resave usd data to arnold .ass files, but by default this is saved as binary .ass files, which is not great for debugging when we want to debug hydra tests VS usd tests
> Tests resaving to a .ass file should save in ascii format for proper debugging

- CHANGELOG.md
- libs/render_delegate/instancer.cpp
- libs/render_delegate/render_delegate.cpp
- libs/render_delegate/utils.cpp
- libs/translator/reader/read_geometry.cpp
- plugins/ndr/parser.cpp
- use const reference as much as possible when calling VtValue::UncheckedGet and VtValue::Get
Fixes #1890
> Avoid memory duplication when using VtArrays.

- libs/render_delegate/config.cpp
- Fix missing semicolon
Admittedly my C++ knowledge is limited and I'm not even sure whether this would be a bug originally or it just ends up being 'cosmetics'. I suspect at the very least that not having a semicolon there might have unexpected behavior - so this at least matches things cosmetically.
> Typo: Fix missing semicolon

- CHANGELOG.md
- libs/translator/reader/read_geometry.cpp
- libs/translator/reader/reader.cpp
- libs/translator/reader/utils.cpp
In a specific use case (where a primitive is not recognized as a xformable schema), we were not applying the transform hierarchy properly. We need to switch the parent & local matrices in the multiplication.
While debugging this, I realized that we were calculating the matrices for all primitive types, including shaders and all. The reason for that is that some primitives are not known as xformables by USD, but still expect a matrix. Since we don't have a fully reliable way to distinguish those, I just added a quick & simple check that skips this calculation for UsdShadeShaders, which are probably the most frequent prim type in usd scenes, and that definitely don't need a useless matrix computation.
I cannot add a test for this since the problem …
> Fix transform hierarchies for non-xformable primitives

- CHANGELOG.md
- libs/translator/writer/prim_writer.cpp
Before we author materials, we verify if the shader mask is enabled. This is needed to add an option in mayaUSD to skip shaders export. 
Since this is changing the behaviour, in a way that skips some nodes when usd files are authored, I'm not considering it for the fix branch
Fixes #1903
> Writer skips materials when the shader mask is disabled

- CHANGELOG.md
- libs/translator/reader/read_geometry.cpp
- libs/translator/reader/utils.cpp
- libs/translator/reader/utils.h
When we read the amount of time keys (primvars:arnold:deform_keys), we no longer check the primvar interpolation.
This is now returning the same result as in the render delegate
Fixes #1908
> Read deform_keys independantly of the primvar interpolation

- CHANGELOG.md
- libs/translator/reader/reader.cpp
During procedural interactive updates, we were always returning true in GetPrimVisiblity, because of a previous optimization.
This PR just ensures that we call the procedural function IsPrimVisible function when we're in update mode. This fixes internal ticket MAXTOA-1777
Fixes #1912
> Fix prims visibility during procedural updates

- libs/translator/writer/write_geometry.cpp
We were taking into account the use case where the vertex attributes had a nullptr array pointer, but we must also consider the use case where they have a zero-element array, as Arnold seems to be setting this kind of arrays by default. This is needed to handle maxUSD exports in a better way
Fixes #1914
> Ensure polymesh topology attributes are not written to USD when not set

- CHANGELOG.md
- libs/translator/reader/reader.cpp
The diff looks worse than what is actually changed in this PR, due to the indentation.
When the reader's Update function is called, instead of explicitely calling ReadPrimitive on the modified prims, we now call ReadStage again. This way we don't need to duplicate all the hierarchy traversal code.
To support the use of ReadStage for updates, a few changes had to be done : 
- The first part of ReadStage that was initializing data (masks, stage, etc...) is only done for the first render, and skipped during updates.
- most of TraverseStage code is moved to a sub-function "TraverseNodes" that can have an input filter of nodes to translate. During a first render, TraverseNodes will be called as it used to be done before.
- When TraverseStage is called …
> Support procedural updates of stage hierarchy

- CHANGELOG.md
- libs/common/constant_strings.h
- libs/translator/reader/read_geometry.cpp
During procedural updates of usd geometries, we were always setting smoothing and subdiv_iterations back to the desired default value, before the attributes were eventually set explicitely during ReadArnoldParameters.
This PR only resets the attribute values if we find that they're not explicitely set as primvars:arnold:subdiv_iterations and primvars:arnold:smoothing, in which case the attributes would be set during ReadArnoldParameters
Issues fixed in this pull request
Fixes #1929
> Ensure subdiv_iterations is not set uselessly during procedural updates

- CHANGELOG.md
- libs/render_delegate/mesh.cpp
When we convert some primvar we might expect the same number of elements as the points. If the number of values is incorrect the iteration end up extracting an empty VtValue with an UncheckedGet which leads to a crash.
 This patch just make sure the VtValue is not empty before calling UncheckedGet.
Fixes #1932
> Check if the VtValue is empty before doing a UncheckedGet

- CHANGELOG.md
- libs/render_delegate/render_delegate.cpp
- libs/render_delegate/render_delegate.h
- plugins/render_delegate/renderer_plugin.cpp
For batch renders of the render delegate we now use a batch render session instead of an interactive one, in order to optimize memory consumption.
We do an exception when the husk command line is executed with the -n argument that triggers the rendering of multiple frames in the same render session, which forces us to have an interactive session
Fixes #1918
> Use batch session for single-frame husk renders

- CHANGELOG.md
- plugins/render_delegate/renderer_plugin.cpp
- Before creating the render delegate we check is the environment variable ARNOLD_FORCE_ABORT_ON_LICENSE_FAIL is set and if so we test if the license is available. We don't create the render delegate if the license is not found.
Fixes #1950
> Avoid creating the render delegate if ARNOLD_FORCE_ABORT_ON_LICENSE_FAIL is set and  the license is not found

- plugins/render_delegate/renderer_plugin.cpp
> Fix compilation issue due to header incorrect name

- CHANGELOG.md
I'm splitting the tickets for next releases, to avoid confusions when versions are released
> Moving tickets in changelog

- testsuite/test_0199/README
test 199 needs a small threshold to work in hydra mode. I've been comparing the translated arnold scenes between usd and hydra and everything seems consistent. There is a tiny rounding difference in camera's focus distance, which could be the cause of the diff since the render shows a very bright sun from physical sky
> Allow test 199 to work in hydra mode

- testsuite/test_0208/README
- testsuite/test_0208/data/scene.ass
- testsuite/test_0208/data/test.cpp
This PR modifies test_0208 so that it can work in hydra mode.
The difference between usd and hydra is that the later filters out the materials that are not assigned to any geometry. This c++ test was relying on some unconnected shaders from being loaded, so I connected them and adapted their name.
> Fix test_0208 to work in hydra mode

- CHANGELOG.md
- libs/common/rendersettings_utils.cpp
- libs/render_delegate/reader.cpp
- libs/translator/reader/read_options.cpp
- testsuite/test_0203/README
I'm moving the code from the translator option's reader to get the camera from the render settings, to the common code for render settings. 
Also, the hydra reader now calls `ChooseRenderSettings` with the render settings primitive set by the procedural. 
This allows to render test_0203 in hydra mode
Fixes #2003
> Choose render settings primitive through hydra scene loader

- testsuite/test_0042/data/sphere.usd
- testsuite/test_0181/data/test.usda
- testsuite/test_0192/README
- testsuite/test_0192/data/scene.usda
- testsuite/test_0193/README
- testsuite/test_0193/data/scene.usda
Several tests were still relying on the old formatting (without the inputs namespace), this PR updates some of them. 
tests 192 and 193 are now succeeding in hydra mode (hydra doesn't support the old format)
> Update light attribute names in several tests

- CHANGELOG.md
- libs/render_delegate/render_pass.cpp
Changes proposed in this pull request
To enable the half float we add HALF at the end of the output aov line.
Fixes #1989
> Enable the use of half aovs in the render delegate when rendering custom products

- CHANGELOG.md
- libs/translator/reader/read_light.cpp
- libs/translator/writer/registry.cpp
- libs/translator/writer/write_light.cpp
- libs/translator/writer/write_light.h
- testsuite/test_0075/README
- testsuite/test_0092/README
Instead of authoring spot & photometric lights to USD as ArnoldSpotLight and ArnoldPhotometricLight schemas (which aren't supported in hydra), we author them as Sphere lights with ShapingAPI
This allows to run tests 75 and 92 in hydra mode
Fixes #2008
> Write spot and photometric lights as UsdLux schemas

- CHANGELOG.md
- libs/render_delegate/reader.cpp
- libs/render_delegate/render_delegate.h
- testsuite/test_0176/README
In this PR, when a procedural is used in hydra mode, we check its transform matrix, and apply it to the imaging delegate as a root transform. 
Also, when a shape node is created, we apply the same logic as the usd translator and propagate the node id integer to all children.
Both these changes allow test_0176 to pass in hydra mode
Fixes #2017
> Set root transform & node id in the hydra procedural

- CHANGELOG.md
- libs/render_delegate/light.cpp
- libs/translator/reader/read_light.cpp
- testsuite/test_0116/README
- testsuite/test_0190/README
In the delegate, we were not taking into account treatAsPoint in spot lights. 
For point & photometric lights sets the radius to 0 and ignores the normalize attribute, so I'm porting the same thing for spot lights (which the usd procedural is already doing).
This enables test 190 and 116 in hydra mode
Fixes #2010
> Support treatAsPoint in spot light

- CHANGELOG.md
- libs/render_delegate/reader.cpp
- libs/render_delegate/render_delegate.cpp
- testsuite/test_0167/README
The hydra reader must call SetRenderTags on the render delegate with the expected purpose ("render" by default), so that e.g. proxy geometries are skipped from the render. For some reason, primitives with a default purpose don't show with a "default" render tag, but "geometry", so I need to add this value to the expected render tags.
Also, TrackRenderTag was doing nothing in "batch" context, and this check was added in the first draft of the hydra procedural, so I'm assuming we can reintroduce it back given the hydra testsuite is working as expected. 
This allows to run test_0167 in hydra mode
Fixes #2019
> Support purpose in the hydra procedural

- CHANGELOG.md
- libs/common/shape_utils.cpp
- libs/render_delegate/native_rprim.cpp
- libs/render_delegate/native_rprim.h
- libs/render_delegate/utils.cpp
- plugins/usd_imaging/shape_adapter.cpp
- testsuite/test_0090/README
- testsuite/test_0100/README
- testsuite/test_1331/README
The delegate code for native_rprims (used for arnold shapes, like ArnoldUsd, ArnoldProcedural, etc...) wasn't supporting properly some attributes, like visibility and sidedness. 
The code was a bit different than other parts of the code, and hadn't been touched for some time. I tried to make it consistent with our other prim types (mesh, procedural_custom, etc...). This fixes test_1331, test_0090 and test_0100
Fixes #2051 
Fixes #2053
> Visibility and sidedness attributes not supported in Arnold native hydra prims

- testsuite/test_0043/README
- testsuite/test_0043/data/proc.usd
- testsuite/test_0161/data/nested_proc.usda
- testsuite/test_0162/data/nested_proc.usda
- replace arnold:matrix with a usd transform in the tests
- This makes test_0043 pass the hydra testsuite.
Fixes #2065
> Replace arnold:matrix with a usd transform in the tests

- CHANGELOG.md
- libs/translator/reader/read_geometry.cpp
- libs/translator/reader/utils.cpp
- libs/translator/reader/utils.h
In order to skip the user data "normals" for meshes & curves in ReadPrimvars, I'm using the existing PrimvarsRemappers classes.
I'm adding a function to determine if a given primvar should be skipped. We're no longer getting the user data in resaved ass files, and it doesn't harm the testsuite
Fixes #2067
> Skip authoring useless "normals" user data on meshes

- CHANGELOG.md
- libs/render_delegate/render_delegate.cpp
- libs/render_delegate/render_pass.cpp
When `_Execute` is being invoked over and over in the render delegate, even sometimes when a render is in progress without any real change, we need to check if specific things have changed, and if they do we make it so that the render is interrupted to update them. 
Here we were constantly setting a couple of options parameters (pixel_aspect_ratio and subdiv_camera) without even interrupting the render. Worse, with the default use case of no subdiv_camera, we were calling AiNodeResetParameter on it, which currently doesn't have all the checks we do in AiNodeSet*, so Arnold constantly thinks that the options have changed, even during iterations.
Finally, in ShouldSkipIteration I'm now calling ProcessConnections all the time, instead of checking the boolean value "skip". In a separate task, …
> Ensure options attributes are not set while a render is in progress

- CHANGELOG.md
- libs/common/rendersettings_utils.cpp
- libs/render_delegate/render_pass.cpp
In the past we used to assign imagers only to the beauty driver. This was changed at some point, they should be assigned to all drivers, and the attribute "layer_selection" can eventually filter out which AOVs are affected by this imager.
The code in the procedural, as well as the render delegate was still using the previous logic, and this was causing problems when rendering through husk with an arnold product type.
Fixes #2084
> Imagers should be applied to all drivers

- CHANGELOG.md
- libs/common/constant_strings.h
- libs/render_delegate/camera.cpp
- libs/render_delegate/camera.h
- libs/translator/reader/read_camera.cpp
- libs/translator/writer/registry.cpp
- libs/translator/writer/write_camera.cpp
- libs/translator/writer/write_camera.h
- testsuite/test_0054/README
- testsuite/test_0106/README
We were previously relying on arnold schemas for cameras (spherical, cylindrical, fisheye, etc..), which isn't supported in hydra.
Instead of adding usdImaging support for these schemas, we choose instead to rely on the builtin camera primitives, and add an attribute specifying the arnold camera type in the prim. Then, all the arnold attributes are already authored with the arnold namespace so there's not much to change. This PR does the required changes in :
- the usd writer, when e.g. a spherical_camera is authored to usd, it's now saved as a usd builtin cam
- the usd reader, when a usd camera is loaded, we check the attribute `primvars:arnold:camera` to check the camera name
- the render delegate, we also check the arnold camera attribute, to …
> Support arnold cameras in hydra

- CHANGELOG.md
- libs/translator/writer/prim_writer.cpp
- testsuite/test_0063/README
In this PR, when a shader array attributes is authored to USD with multiple keys, we author all the values (elements * keys) in a single time sample. Currently, the only arnold shader supporting animated values is matrix_interpolate  for attribute attribute "matrix". It renders all array values independantly of them being keys or elements, so there's nothing to do on the reader side.
This allows to render test_0063 in hydra mode.
Fixes #2080
> Author animated shader attributes in a way that they can render in hydra

- CHANGELOG.md
- libs/render_delegate/reader.cpp
- libs/render_delegate/render_delegate.cpp
- libs/render_delegate/render_delegate.h
- libs/render_delegate/render_param.cpp
- libs/render_delegate/render_param.h
- libs/render_delegate/render_pass.cpp
This PR changes the ShouldSkipIteration function logic to be UpdateSceneChanges that will return true if the scene has changed. This function was previously returning the opposite value than what it was supposed to do. I'm thus updating the different parts of the code that are calling it.
Also, the previous logic was this if there was nothing updated in the scene, we would return "Converging" instead of calling Render(), but that's not correct. We need this callback to be invoked even if nothing has changed in the scene, as this function just checks the render status and does the necessary if the render has finished, is restarting, etc.... The reason it was working was precisely because the logic in ShouldSkipIteration was inverted, and  given the …
> Ensure the render callback is always invoked

- libs/translator/reader/read_shader.h
- libs/translator/reader/reader.cpp
- testsuite/test_2072.1/README
- testsuite/test_2072.1/data/test.cpp
- testsuite/test_2072.2/README
- testsuite/test_2072.2/data/test.cpp
This is a work in progress, it does not work with hydra as we should store the shaders and imagers under NodeGraph or Materials.
- let the shader reader read the imagers
- avoid the creation of nodes that are not compatible with the read mask.
Fixes #2072
> Read shaders and imagers with masks (WIP)

- CHANGELOG.md
- libs/translator/reader/reader.cpp
Before we register the TfNotice callback, we need to ensure we didn't already do it. Since we go through the same function at each procedural update, this could happen and end up causing crashes with MaxUSD. This fixes the internal ticket MAXTOA-1824
> Ensure we don't register the TfNotice callback twice MAXTOA-1824

- SConstruct
The TIMELIMIT variable is taken into account in our testsuite scripts, but it wasn't exposed in the Sconstruct. This PR adds it, with a default time of 5mn. This will kill tests that last longer.
> Expose TIMELIMIT variable

- CHANGELOG.md
- libs/render_delegate/mesh.cpp
We were trying to get the subdiv_iterations attribute explicitely as an integer, which isn't correct as it's a BYTE attribute.
This removes the spurious warning in hydra.
Also, I saw we were still forcing polymesh "smoothing" to true when a new mesh is created. While this is not incorrect, it's not needed anymore since Arnold 7.2.0.0, when smoothing has been enabled by default
Fixes #2102
> Remove hydra warning subdiv_iterations: use type BYTE, not INT

- CHANGELOG.md
- libs/translator/reader/read_geometry.cpp
- libs/translator/reader/reader.cpp
In the procedural, we need to handle in a particular way the primitives that were previously visible and that are interactively modified to become hidden. In general, when a primitive is hidden we prune it along with its children and skip the export.
But in this case, we must ensure the primitive is re-exported so that the visibility (and eventual other attributes) can be properly updated in the arnold side. 
In order to apply this logic to all geometry types, I realized it would cause yet another lot of duplication, so I did instead some code factorization through a function `_ReadGenericShape` containing a list of steps that are common to all shapes (apart from the instancer which is a bit different).
Fixes …
> Support visiblity updates in interactive procedural changes

- CHANGELOG.md
- libs/translator/reader/reader.cpp
When a material is updated interactively with the procedural, we can't just update the material primitives. We must also update the geometries which are assigned to this material, so that the arnold shapes have the correct shader assignment.
In this PR, we add a special case for this, and add to the list of modified nodes, all the geometries bound to the modified materials
Fixes #2094
> Support material interactive updates in the procedural

- libs/common/common_utils.h
- libs/translator/reader/read_shader.h
In a recent commit we've started using the value AI_NODE_IMAGER which didn't exist before Arnold 7.3.0
> Fix build error with older versions of arnold

- CHANGELOG.md
- libs/render_delegate/reader.cpp
- libs/render_delegate/reader.h
We need to define the Update function of the render delegate reader.
Inside, we call ApplyPendingUpdates of the imaging delegate and we sync the scene.
To do that, I'm moving some Hydra structures as members of the reader class, so that they're kept around during the IPR session.
Fixes #2107 
> Support procedural updates in hydra mode

- CHANGELOG.md
- plugins/procedural/main.cpp
This PR adds a boolean parameter "hydra" to the procedural. When enabled, this will switch to using a hydra procedural by default. This could then be overridden by the environment variable
Fixes #2109
> Add hydra attribute to the usd procedural

- CHANGELOG.md
- libs/translator/writer/writer.cpp
In the USD writer, when we create the usd hierarchy based on the node name, we recursively create the parent prims until we reach a primitive which path is `SdfPath::AbsoluteRootPath()`. However, we have a scenario where the path can be empty, in which case it will go in an endless recursive loop calling `UsdArnoldWriter::CreateScopeHierarchy`.
To fix this, in both `CreateHierarchy` and `CreateScopeHierarchy`, I'm also checking if the SdfPath is empty. This fixes the crashes with the mayaUSD repro
Fixes #2133
> Fix crash when the root primitive is invalid

- libs/translator/writer/prim_writer.h
AI_NODE_IMAGER was not defined on older versions of Arnold. We're handling this in common_utils.h.
But recently we started to use this variable in prim_writer.h which does not include the above file, which prevents from building in older versions of Arnold. I'm fixing it here
> Fix build issue on older versions of Arnold

- testsuite/test_0245/data/test.py
We're missing some verbosity in test_0245 to understand what could fail
> Add verbosity to test 245

- plugins/procedural/main.cpp
- schemas/createSchemaFile.py
The changes done for #2088 were missing a use case : when the schemas are generated there might not be a "usd" node entry yet (which is the case when arnold-usd is compiled through arnold core). Also, when that happens the usd procedural has not been built as it needs the schemas to be generated first.
Therefore we need to explicitely add the schema ArnoldUsd to the schemas file. This is not ideal as we need to hardcode the usd procedural attributes list. I added a comment in the procedural `node_parameters` function so that every time an attribute is added it's ported to the schemas script.
I could have done all this only when the usd node entry is not found, but I think it's better to do it all the time. Otherwise we're using the node entry that …
> Ensure the ArnoldUsd schema is properly generated

- schemas/createSchemaFile.py
In #2143 I enforced the filename attribute to be an asset attribute, which was different from before (it was a string). Because of that, there are issues in Maya when exporting such a node to usd, with error messages about string VS asset.
My first attempts to make it work as an asset aren't working and causing other issues, so I'll make another ticket to make this attribute an asset, and here I'll roll it back to the previous behaviour
> Restore arnoldUsd filename to be a string attribute

- CHANGELOG.md
- libs/render_delegate/reader.cpp
- libs/render_delegate/render_delegate.cpp
- libs/render_delegate/render_delegate.h
- libs/render_delegate/render_pass.cpp
The changes introduced in #2079 were actually pretty wrong, and caused by a miss-understanding of what the function was doing. This PR reverts most of it, and adds the explanations and comments that were missing in the original code.
In the function I had renamed as `UpdateSceneChanges`, some hydra primitives are marked as dirty. I thought the Sync function would be called immediately, thus updating the arnold scene, but it's actually called later on.  So for clarity I'm renaming it as `HasPendingChanges` which tells us that a Sync call is going to happen shortly. In this case, we don't want to start the render just yet, cause we know the scene might change. For interactive renders it's not so bad because we can interrupt and restart the render to …
> Fix handling of hydra updates in batch renders

- libs/render_delegate/render_param.cpp
- We remove AI_ERROR_UNAVAILABLE_DEVICE that is now deprecated.
> Remove AI_ERROR_UNAVAILABLE_DEVICE from Arnold version higher that 7.3

- CHANGELOG.md
- libs/render_delegate/mesh.cpp
When positions are modified in interactive renders, with a mesh having subdivision, we must ensure that all the primvars are updated too. Otherwise it will trigger a bug in the arnold side ARNOLD-15709
Fixes #2159
> User data errors with deformed meshes and subdivision

- CHANGELOG.md
- libs/common/materials_utils.cpp
This PR adds support for the OSL code generated for image shaders by MaterialX 1.38.10.
In MaterialX 1.38.8 the OSL shader generator will create _struct texturesource_ parameters such as :
```
textureresource  shader_file = {\"\", \"\"}
[[
string widget = \"filename\"
]],
```
In MaterialX 1.38.10 the shader generator will split the textureresource shader in two parameters :
```
string shader_file = \"\"
[[
string widget = \"filename\"
]],
string shader_file_colorspace = \"\"
[[
string widget = \"colorspace\"
]],
```
> Support OSL code generated from image shaders in MaterialX 1.38.10

- libs/common/constant_strings.h
- libs/common/materials_utils.cpp
The fix proposed in #2160 is failing to set the colorspace on the MaterialX triplanar node, as the file parameter is named differently. I verified that this fix is passing the testsuite.
> Fix MaterialX triplanar colorspace issue

- CHANGELOG.md
- libs/render_delegate/basis_curves.cpp
- libs/render_delegate/instancer.cpp
- libs/render_delegate/instancer.h
- libs/render_delegate/utils.cpp
- libs/render_delegate/utils.h
- In USD >= 24.08 the SamplePrimvar function returns different values than before, omitting the shutter boundaries. This leads to several test failures. This PR adds code to resamples the values returned by SamplePrimvar such that they work with what Arnold expects, equally spaced values in the shutter range.
Fixes #2168
> Resample the values returned by SamplePrimvar 

- libs/render_delegate/shape.cpp
- with a ifdef we re-enable the previous render tags handling behaviour for usd versions < 24.08 
- we don't add a changelog entry since this is a fix for https://github.com/Autodesk/arnold-usd/pull/2171
Fixes #2178
> re-enable checking the DirtyRenderTag tag for versions < 24.08

- CHANGELOG.md
- libs/render_delegate/render_delegate.cpp
- libs/render_delegate/render_delegate.h
We were previously returning true in render delegate's `IsPauseSupported` and interrupting the render when pause was called. Then, for "resume render" we were simply restarting it from scratch, since arnold currently doesn't support pause & resume rendering. This PR removes the "pause" functions from our render delegate (which defaults to pause not being supported), and instead returns true in `IsStopSupported`. In Solaris, this will replace the previous "Pause Render" menu with "Stop Render".
It then removes several issues that happened because of the render pause (e.g. render restarting in Solaris when the AOVs are changed in Houdini 20.5)
Fixes #2177
> Declare render delegate "stop render" instead of pause

- CHANGELOG.md
- SConstruct
- tools/test/testsuite.py
- Write junit report if the JUNIT_TESTSUITE_NAME arg is set
- Re-enable the report on fail only
Fixes #2183
> Write junit report 

- SConstruct
The build variable BOOST_INCLUDE is currently defaulting to a path meant for boost 1.61. We always set this variable when building arnold-usd, but with latest versions of USD that don't need boost this is a problem because the variable isn't set anymore and the default path doesn't exist.
By setting a default path of "." (as we have for BOOST_LIB) it fixes the issue, and really makes the variable optional
> Use better default for BOOST_INCLUDE build variable

- plugins/render_delegate/SConscript
- plugins/scene_delegate/SConscript
Recent changes in our build scripts broke the compilation of the scene delegate and render delegate plugins.
This PR ports the changes to these scripts
> Fix recent build issues in arnold-usd plugins

- CHANGELOG.md
- libs/render_delegate/reader.cpp
- libs/translator/reader/reader.cpp
- Add profile blocks in read_stage functions
Fixes #2190
> Save read stage time in the stats

- libs/common/constant_strings.h
- libs/render_delegate/light.cpp
- libs/translator/reader/read_light.cpp
In #2176  we have changed the current behaviour of distant lights normalize attributes.
We want to add a global option to roll back to the previous behaviour. 
Note that we first need this attribute to be added in arnold core before we can make a test for that, otherwise the current code sees that this attribute doesn't exist in the options and rolls back to ignore the normalize.
> Consider global option to roll back distant lights normalize

- testsuite/CMakeLists.txt
- tools/test/testsuite.py
- When using cmake, we compile the procedural in a different directory than scons. In order to run the testsuite on different procedural location we add 2 new environment variables that, if defined, are going to be used by the testsuite to override ARNOLD_PLUGIN_PATH and PXR_PLUGINPATH_NAME:
- TESTSUITE_ ARNOLD_PLUGIN_PATH -> ARNOLD_PLUGIN_PATH
- TESTSUITE_PXR_PLUGINPATH_NAME -> PXR_PLUGINPATH_NAME
- We use those variables in cmake to run the testsuite with `make testsuite`
Fixes #2195
> Add override environment variables for the testsuite to use with cmake

- libs/render_delegate/render_delegate.cpp
- libs/render_delegate/render_delegate.h
The changes in #2177 are not compiling with USD 21.11, because the IsStopped API didn't exist yet
> Fix build issue in older versions of USD

- libs/render_delegate/render_delegate.cpp
- libs/render_delegate/render_delegate.h
- libs/render_delegate/rprim.h
#2199 only fixes a single function, here I fix the remaining functions
> Fix build issue in older versions of USD (#2199)

- CHANGELOG.md
- libs/render_delegate/reader.cpp
- libs/render_delegate/reader.h
In the hydra procedural, we could be creating a dummy usd camera, just to assign it to our usd imaging delegate in `SetCameraForSampling`. Since the input usd stage is supposed to be read-only when we read through a stage cache, we must handle it differently. Here we subclass UsdImagingDelegate and redefine the function `GetCameraParamValue` so that it can return directly the shutter range when requested. To do that we must pass a dummy primitive name in `SetCameraForSampling`, but this shouldn't be a problem as the name isn't used anywhere, except in `GetCurrentTimeSamplingInterval` . It first verifies that the "render camera path" isn't empty (which is why we need to set a dummy name), and then calls `GetCameraParamValue` for `sutterOpen` and …
> Hydra procedural should not modify the usd stage for shutter range

- CHANGELOG.md
- libs/common/materials_utils.cpp
In `ReadMtlxOslShader`, as we call `AddConnection` to connect parameters, we were not finding the arnold node due to a naming scope issue. Now, we do the same as with builtin arnold shaders, and eventually call `MaterialReader::ConnectShader`. This function will eventually add the scope of the material so that we find the right shader.
Fixes #2197
> Fix mtlx texture connection in the render delegate

- libs/render_delegate/mesh.cpp
- Since we share the mesh parameters we have to reset them when the HdMesh is destroyed. The previous way of doing it was to set the parameter array to nullptr which is incorrect. This PR uses the AiNodeResetParameter function to correctly reset the parameter.
Fixes #2214
> Fix incorrect reset of mesh parameters

- CHANGELOG.md
- libs/render_delegate/render_delegate.h
I'm adding a mutex for accessing the _nodeNames map so that it becomes thread-safe
Fixes #2219 
> Fix race condition in hydra node names

- CHANGELOG.md
- libs/render_delegate/camera.cpp
To avoid being in a state where the "previous" camera and the new one coexist, even temporarily, we ensure the previous one is deleted first. We do this by calling SetCamera(nullptr). Then we create the new camera (with the same name but a different type) 
This fixes the warnings in test_0115
Fixes #2218 
> Fix error message in hydra with ortho cameras

- CHANGELOG.md
- libs/render_delegate/nodes/nodes.cpp
When we run the procedural in hydra mode we can see a bunch of 
WARNING |  node "HdArnoldDriverMain" is already installed
We can fix this by checking if the node entry exists before we install it
> Fix runtime warning  "HdArnoldDriverMain is already installed"

- CHANGELOG.md
- libs/translator/reader/read_geometry.cpp
In the usd translator, when we get the list of prototypes, we must ensure they're valid. If some of them are missing, we must skip them to avoid usd crashes
Fixes #2225
> Fixed crash in point instancers with missing prototypes

- CHANGELOG.md
- libs/common/procedural_reader.h
- libs/render_delegate/reader.cpp
- libs/render_delegate/reader.h
- libs/render_delegate/render_delegate.cpp
- libs/render_delegate/render_delegate.h
- libs/translator/reader/reader.cpp
- libs/translator/reader/reader.h
- plugins/procedural/main.cpp
This PR could have been a single liner. In order to fix the logging issue we just need a single test 
`if (_renderDelegateOwnsUniverse) ` before all the code that calls the AiMsgSet* functions. This way, only the render delegate used from hydra (solaris) should initialize the logging.
In my first version, I thought the condition should be about whether there is a procedural parent or not, and we don't have that information when the render delegate is created. So I did a few changes in the constructors, so that we have that setting at the construction of the readers & render delegate. It allows to get rid of the functions SetProceduralParent and SetUniverse, which aren't actually needed, since we never need to modify them after the reader was …
> Hydra procedural breaks the arnold logging settings

- CHANGELOG.md
- libs/render_delegate/render_delegate.cpp
We need to declare RenderSettings in the list of Bprims that are supported by Arnold, even though we're not treating it through a Hd primitive as we do for other primitives types.
The warning also shows for RenderProduct primitives in USD 23.11, but this was fixed in the usd side on recent versions
Fixes #2234
> Remove warnings about RenderSettings prim not supported in hydra mode

- libs/render_delegate/render_delegate.cpp
When I fixed #2234 , I introduced a regression in Solaris. This PR fixes it by only adding renderSettings to the supported prims when we're going through a reader.
Fixes #2234
> Fix render settings error introduced by previous commit

- CHANGELOG.md
- libs/common/procedural_reader.h
- libs/render_delegate/reader.cpp
- libs/render_delegate/reader.h
- libs/translator/reader/reader.cpp
In this PR I'm checking the environment variable HDARNOLD_DEBUG_SCENE and if set we're writing out the arnold scene to a debug file after the usd file was translated, in ReadStage.
Note that, as in the case of the render delegate, the debug file is not directly renderable as it will contain the usd procedural node, as well as all the child nodes. At the moment, this is the best way to get a debug scene and introspect the procedural translation. 
I'm not doing it in the usd procedural at the moment, although it might end up being useful to compare usd VS hydra. But for now this is only for hydra.
While doing this, in my first attempt I was putting this in the base reader class ProceduralReader, and I realized we didn't have a constructor in this …
> Support HDARNOLD_DEBUG_SCENE env var in the hydra procedural

- SConstruct
- testsuite/SConscript
As we have in the arnold testsuite, I'm adding the build variable TESTSUITE_PASSES that can be used to customize it and just render "usd" or "hydra" test. This can be useful for debugging a specific issue and only running one of those tests
> Add build variable for TESTSUITE_PASSES

- CHANGELOG.md
- libs/common/constant_strings.h
- libs/render_delegate/reader.cpp
- plugins/procedural/main.cpp
- schemas/createSchemaFile.py
This PR enables the hydra mode of the usd procedural by default. It also looks for an options attribute "usd_legacy_translation" (to be added in the arnold side) that can force the hydra mode to be disabled. 
The environment variables always take precedence on all these settings
Fixes #2248
> Enable the hydra mode of the procedural by default

- libs/render_delegate/reader.cpp
- libs/render_delegate/reader.h
This PR introduces a first set of changes that look for the environment variable `USDIMAGINGGL_ENGINE_ENABLE_SCENE_INDEX`  and enables the scene index instead of the previous UsdImagingDelegate from older versions of Hydra.
This is a first draft, there are still a few missing bits, like where to set the shutter, the object path, or the purpose.
Fixes #2262
> First support of scene index

- CHANGELOG.md
- libs/render_delegate/reader.cpp
We were missing a changelog in the previous PR, as well as an additional call to ProcessConnections after we do SyncAll
Fixes #2269
> Add changelog for #2269

- libs/render_delegate/reader.cpp
- libs/render_delegate/reader.h
A previous PR introducing scene index isn't compiling with older versions of USD. This PR adds ifdefs to restore the builds as before. Scene index will only work for usd 24.11 and up
Fixes #2262
> Fix compilation issues with older versions of USD

- tools/test/testsuite.py
This PR makes it so that unstable tests don't return an error in the testsuite. This way, we can all the automation to run despite the random failures.
> Prevent unstable tests from failing the CI

- CHANGELOG.md
- libs/render_delegate/config.cpp
As discussed in HtoA ticket HTOA-2279, the current defaults for interactive fps values should be improved. This PR sets them to more appropriate values. In particual, we want a factor of 4 between `interactive_target_fps` and `interactive_target_fps_min`
> Improve interactive fps values

- CHANGELOG.md
- libs/render_delegate/render_delegate.h
It should now be possible to destroy nodes even when they come from a procedural, instead of disabling them as we were doing before
Fixes #2277
> Destroy child nodes from the hydra procedural instead of disabling them

- testsuite/groups
- tools/test/testsuite.py
test_0176 is currently failing way too often on windows, due to random issues.
For the moment we're disabling it, until we find a proper fix
> Skip test_0176 on linux

- CHANGELOG.md
- libs/render_delegate/basis_curves.cpp
- libs/render_delegate/mesh.cpp
- libs/render_delegate/points.cpp
Here, when a geometry is invisible, we skip the translation instead of fully exporting the node and then setting it as invisible.
The testsuite is ok, but we should ensure it works for hidden geometries that are being instantiated.
Fixes #2264
> Skip translation of invisible primitives in the render delegate

- libs/render_delegate/instancer.cpp
- angularVelocities was not recognised in previous versions of USD, we use a local token instead of relying on HdTokens
> Use local token for angularVelocities

- CHANGELOG.md
- libs/common/rendersettings_utils.cpp
- libs/translator/writer/write_options.cpp
In USD we were forcing some default values for GI_diffuse_depth and GI_specular_depth, but not for GI_transmission_depth. 
Here I'm setting it to 8 by default, as it's set in all the arnold plugins (the core defaults to 2). 
I'm also forcing it to be set in the usd writer as for the other 2 attributes
Fixes #2287
> Fix mismatch between USD and Hydra for GI_transmission_depth

- CHANGELOG.md
- libs/render_delegate/reader.cpp
- plugins/procedural/main.cpp
- testsuite/groups
- test_0176 creates multiple HydraReader potentially at the same time and this crashes often. This fix adds a lock at the creation of HydraReader's render index to prevent parallel creation.
> Prevent the parallel creation of the render index

- CHANGELOG.md
- libs/render_delegate/render_delegate.cpp
The stats mode was not being set properly in the render delegate. It was always forced to be "overwrite".
This PR takes into account the provided value, and it also supports string values for this setting, which is what HtoA returns us.
Fixes #2296
> Fix stats mode in the render delegate

- CHANGELOG.md
- libs/translator/reader/read_geometry.cpp
- testsuite/test_1730/data/test.usda
- testsuite/test_2064/data/test.usda
As it is already done in hydra, we also check for attributes `primvars:arnold` on the `ArnoldProceduralCustom` primitives.
I edited test_2064 so that it uses this format and we can track regressions. I also changed one of the attributes in test_1730. I left test_0739 as using the previous format
Fixes #2313
> Support arnold primvars for ArnoldProceduralCustom primitives

- CHANGELOG.md
- libs/common/constant_strings.h
- plugins/procedural/main.cpp
This PR adds the missing metadatas to the usd procedural `filename` attribute. 
One to tell arnold that this string is actually a path, and another to provide the expected list of extensions for file browser in the plugin UIs
Fixes #2318
> Add metadatas path and extension to the usd procedural

- libs/render_delegate/reader.h
- Compile scene index code only with 25.05 and after
> Use scene index on 25.05 and beyond

- CHANGELOG.md
- libs/render_delegate/render_delegate.cpp
In the render delegate constructor, we are disabling CER reports when `isBatch` is enabled. But this variable seems to be always enabled when it's created through the `HydraArnoldReader`, so for procedural & scene format renders.
We only want to do this when the render delegate is owning the universe (e.g. with husk), to ensure no pop-up shows up during batch renders. Otherwise, this is already handled by kick
Fixes #2337
> Don't disable CER reports with the hydra procedural

- CHANGELOG.md
- plugins/procedural/main.cpp
We should not declare the attribute "frame" as triggering a full reloading of the usd procedural. First, it will be much more optimized when moving the timeline to avoid reading the whole usd file again. Second, it prevents a current bug with `AiProceduralExpand` that is making objects disappear in Maya & 3dsMax when we scrub the timeline
Fixes #2352
> Changing the frame should not reinitialize the procedural

- schemas/createSchemaFile.py
There is a mistake in the schemas script, that duplicates some attributes multiple times in the schema.usda file. In theory this shouldn't be too much of an issue, since we run `usdGenSchema` on this file, and it should fix the duplication. But it's still better to have something correct in our files
> Fix indentation in schema script

- SConstruct
> Add NDEBUG when compiling with clang and gcc in opt mode

- CHANGELOG.md
- libs/render_delegate/mesh.cpp
- reset the uvidxs parameter as it might be shared with vidx and reference twice. If it is not reset, after the deletion of the HdMesh the buffers are invalid and the arnold node is pointing to invalid memory.
Fixes #2364
> Fix crash in HdMesh when using indexed uvs and shared arrays

- tools/test/testsuite.py
Backports #2373 
(cherry picked from commit 79a9dfbc64aeda7c74f57678499bf858197406e0)
> Round up "max_failed_unstable" in testsuite and print reasons for the failure (7.4.1)

- tools/test/testsuite.py
Backports #2373 
(cherry picked from commit 79a9dfbc64aeda7c74f57678499bf858197406e0)
> Round up "max_failed_unstable" in testsuite and print reasons for the failure (7.4.3)

- SConstruct
- remove ther `/Zi` flag for MSVC SCons builds to prevent build errors when running multiple parallel builds
Fixes #2380 
> Remove pdb generation from debug builds

- CHANGELOG.md
- libs/common/materials_utils.cpp
- Skip additional metadata parameters [introduced in USD 25.05](https://github.com/PixarAnimationStudios/OpenUSD/blob/14e978d726ac5cac01ba15eade7da42c69a1a814/CHANGELOG.md?plain=1#L905). 
Fixes #2392
> Fix the typeName:parameter arnold usd warnings.

- CHANGELOG.md
- libs/common/constant_strings.h
- libs/render_delegate/config.cpp
- libs/render_delegate/config.h
- libs/render_delegate/render_delegate.cpp
- libs/translator/reader/read_geometry.cpp
- plugins/procedural/main.cpp
- testsuite/test_0158/data/test.ass
- testsuite/test_0160/data/test.ass
- testsuite/test_0161/data/scene.ass
- testsuite/test_0162/data/scene.ass
- testsuite/test_0163/data/test.ass
- testsuite/test_0164/data/test.ass
- testsuite/test_0165/data/test.ass
- testsuite/test_0167/data/test.ass
- testsuite/test_0168/data/scene.ass
- testsuite/test_0195/data/test.ass
- testsuite/test_0204/data/test.ass
- testsuite/test_0205/data/test.ass
- testsuite/test_0206/data/test.ass
- testsuite/test_0207/data/test.ass
- testsuite/test_0317/data/test.usda
- testsuite/test_1546/data/test.ass
This PR replaces all ocurrences of procedural_searchpath and texture_searchpath and replaces it with a single asset_searchpath, to match an unreleased change in arnold.
I removed it from a bunch of tests that had a dummy, local path on these attributes.
> Replace procedural & texture search path with asset_searchpath
